### ISSUE TITLE
PerspexVS does not detect changes to output assembly name

### ISSUE THREAD

**Issue by ghost** [AvaloniaUI/AvaloniaVS#10]
When the designer is loaded, it will pull information about the output assembly so that the designer can do it' magic. If while a designer is open, a person decides to rename their output assembly, it is possible that the previously open designer view will fail or will not update with changes.

**Comment by ImaBrokeDude** [comment]
This is extension level. I believe we would need to listen to events from the iVsHierarcy to detect these changes.
