### ISSUE TITLE
Avalonia Designer doesn't start

### ISSUE THREAD

**Issue by MRmlik12** [AvaloniaUI/AvaloniaVS#101]
Avalonia on visual studio 2019 didn't run perfectly and trow errors
Logs
https://pastebin.com/4MaHJ7a6
![help](https://user-images.githubusercontent.com/44818681/57966166-e5b89500-794e-11e9-878f-09907f39b445.JPG)

**Comment by grokys** [comment]
> Moved this to the AvaloniaVS repository

Hi @MRmlik12,

The pastebin you posted says it's private. Could you make it public  or post the log to https://gist.github.com please?

**Comment by MRmlik12** [comment]
> > Moved this to the AvaloniaVS repository
> 
> Hi @MRmlik12,
> 
> The pastebin you posted says it's private. Could you make it public or post the log to https://gist.github.com please?

Ok, I'm created new public link https://gist.github.com/MRmlik12/ea4cc8db30efe59dee7de69bd58fa92c

**Comment by grokys** [comment]
Thanks!

Ok, the error seems to be this line:

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Universal%20Boottle, Culture=neutral, PublicKeyToken=null'. Nie moľna odnale«† okrelonego pliku."
```

Does `Universal Boottle.dll` mean anything to you? The assembly can't be loaded. I suspect this may be because it has spaces in its filename: you'll notice that there's a `%20` in there instead of a space.

If this is one of your assemblies, could you try removing the space from the filename?

**Comment by MRmlik12** [comment]
@grokys Thank you very much for solving my problem :)! First I must changed Assembly name and works.

**Comment by grokys** [comment]
Great! Glad it's solved. I've opened https://github.com/AvaloniaUI/Avalonia/issues/2544 to track the issue with us not handling spaces in assembly names.
