### ISSUE TITLE
Quick find and navigating to previous file doesn't work with xaml editor

### ISSUE THREAD

**Issue by skatanski** [AvaloniaUI/AvaloniaVS#108]
Visual Studio 2019 16.3.5

"Quick Find" launched by Ctrl + F opens "Find and Replace" instead of "Quick Find" when focus is in xaml code editor window
"Navigate Back" launched by Ctrl + - omits all previously opened *.xaml files and goes straight to nearest *.cs file

It doesn't work in other VS versions as well and it doesn't seem to be working in VS2017.

In WPF editor it works fine.

**Comment by grokys** [comment]
Got a fix for Quick Find in #116. Going to move the Navigate Back/Forward issue to a new issue to track it separately.
