### ISSUE TITLE
PerspexVS does not detect changes to current working document

### ISSUE THREAD

**Issue by ghost** [AvaloniaUI/AvaloniaVS#11]
In the event that a person renamed the document that the designer is targeting, it is possible the designer might fail because it is referencing a non-existent file, or cause the old file to be recreated on save, We will need to be able to handle this.

**Comment by ImaBrokeDude** [comment]
https://msdn.microsoft.com/en-us/library/8f9kffa8.aspx

Seem like this might help a bit as well as solve #10
