### ISSUE TITLE
Enter key moves cursor to begin of the line when selected from completion set

### ISSUE THREAD

**Issue by donandren** [AvaloniaUI/AvaloniaVS#127]
repro:

- type: `<Gri`
- press `Enter` (to select from completion set 'Grid'
- cursor is not possitioned after `Grid`, but before `<Grid`

this bug was recently introduced by a code that has nothing obvious todo with `Enter `key at first glance - https://github.com/AvaloniaUI/AvaloniaVS/blob/35152c4cb2691d7541830675f89ee77f28b209ec/AvaloniaVS/Views/EditorHostPane.cs#L67

comment this line and everything works as expected

**Comment by waliarubal** [comment]
Not just enter, space bar would also move cursor to next line. Had this issue with nightly builds. Haven't checked it yet with latest 0.9 of extension. I hope its fixed in it.

**Comment by ShadowDancer** [comment]
@donandren looks like this issue is resolved?
