### ISSUE TITLE
Xaml designer not working when targeting net472

### ISSUE THREAD

**Issue by georgiuk** [AvaloniaUI/AvaloniaVS#129]
Hello,
I have a project (executable) that targets net472 . The designer does not work. 
The  message on the designer surface is "No Executable". "Reference the library from an executable or wait for the solution to finish loading." 
On the Avalonia Diagnostics Output I get 
17:59:17.481 [Information] 0 Stopping previewer process
17:59:28.020 [Error]  No executable found

I use version 0.9.1 and running the app works without a problem.

**Comment by grokys** [comment]
> Transferred to AvaloniaVS repository.

Yeah, at the moment only netcore targets are supported. You might want to try dual targeting your application if possible.

However since https://github.com/AvaloniaUI/AvaloniaVS/pull/120 has been merged, maybe we can lift this restriction.

**Comment by georgiuk** [comment]
Not possible to dual target. We migrate our code to Core but we are not there yet. 
Anyway I will try to design in a dummy project and transfer the xaml to the actual project.

**Comment by grokys** [comment]
I'll take a look into lifting the restriction on net framework projects, will probably after xmas though.

**Comment by georgiuk** [comment]
OK. Great.

**Comment by bradder555** [comment]
I'm having the same issue trying to target .NET Core 3.1, i'm using FSharp over CSharp, will that have anything to do with it?

**Comment by daniel-lerch** [comment]
@bradder555 I just did some research for another issue and found the reason why F# is not supported. [SolutionsService.cs:71](https://github.com/AvaloniaUI/AvaloniaVS/blob/8132fcfa4da7978c13a8899175a31cd1d712fbc7/AvaloniaVS/Services/SolutionService.cs#L71) takes only files with an extension `.csproj`. You would have to do some tests but in best case it could be fixed by checking for `.csproj` or `.fsproj`.

**Comment by JeReT** [comment]
@grokys 
> I'll take a look into lifting the restriction on net framework projects, will probably after xmas though.

xmas 2019 is over already... would you mind to take a look?

**Comment by grokys** [comment]
I'm stuck at home during a pandemic with a 17-month old child whose nursery is closed while both I and her mum are supposed to be doing 2 full-time jobs, so unlikely to happen.

**Comment by jjxtra** [comment]
Same error with .net 6 app, weird...
