### ISSUE TITLE
Autocomplete shouldn't list internal properties

### ISSUE THREAD

**Issue by FoggyFinder** [AvaloniaUI/AvaloniaVS#130]
For example. `RowDefinitionsDirty`:

![sample](https://user-images.githubusercontent.com/16510738/71345202-57a02f00-256d-11ea-814f-d08fdd6c74fb.jpg)

If one have set the property then runtime exception will be thrown:

```
Unhandled exception. System.MethodAccessException: Attempt by method 'Views.MainWindow.!XamlIlPopulate(System.IServiceProvider, Views.MainWindow)' to access method 'Avalonia.Controls.Grid.set_RowDefinitionsDirty(Boolean)' failed.
```

**Comment by rstm-sf** [comment]
What about this in nightly builds? AvaloniaUI/Avalonia#4985

**Comment by FoggyFinder** [comment]
dunno, I don't have time to check it now

**Comment by FoggyFinder** [comment]
Checked - the same

**Comment by rstm-sf** [comment]
Hello! With avalonia 0.10 this works for me
![image](https://user-images.githubusercontent.com/2669927/107563312-f6647080-6bf1-11eb-83f9-bd73f90e8d85.png)

**Comment by rstm-sf** [comment]
It seems that additional checks on family ​​need to be made 
https://github.com/0xd4d/dnlib/blob/4e0837cb0f4319ffbcdd1642d1973fce203b2177/src/DotNet/MethodAttributes.cs#L20-L26
