### ISSUE TITLE
Designer not loading

### ISSUE THREAD

**Issue by DhanushVinayUttarkar** [AvaloniaUI/AvaloniaVS#132]
I simply created new avalonia project on visual studio 2017 and the designer didn't load (checked it for about an hour)

![No_load](https://user-images.githubusercontent.com/19226214/72592632-f92a5e80-3928-11ea-9936-18a8b4dcee2d.PNG)

when I ran it, It gave me this error

> The program '[7864] dotnet.exe' has exited with code -2147450751 (0x80008081).

**Comment by ezruneko** [comment]
Me too on VS2019 16.5.4

**Comment by AngelicosPhosphoros** [comment]
Me too on VS2019 16.16.0

**Comment by wberdowski** [comment]
Same issue on VS2019 16.7.4

**Comment by BadKiko** [comment]
13:27:55.911 [Error] 243192 <= "   at NoisePower.ViewModels.MainWindowViewModel..ctor()"
13:27:55.915 [Error] 243192 <= "   at Builder_3597e0c6f0f040bf9c0bfa3bd40fe54f_avares://NoisePower/Designer/Fake.xaml.__AvaloniaXamlIlPopulate(System.IServiceProvider, NoisePower.Views.MainWindow)"
13:27:55.917 [Error] 243192 <= "   at NoisePower.Views.MainWindow.!XamlIlPopulateTrampoline(NoisePower.Views.MainWindow)"
13:27:55.921 [Error] 243192 <= "   at NoisePower.Views.MainWindow.InitializeComponent()"
13:27:55.924 [Error] 243192 <= "   at NoisePower.Views.MainWindow..ctor()"

**Comment by exe2k** [comment]
same here VS 16.11.8
Designer ls loading...

**Comment by maxkatz6** [comment]
@BadKiko problem in your code, NoisePower.ViewModels.MainWindowViewModel fails.
@exe2k please check logs, with high probability there is a problem in your code.

**Comment by zlnimda** [comment]
Same problem on vs 2019 16.11.18, lastest avaloniavs extension

Designer was working fine recently, and now keep being stuck at "Designer loading".
Logs (setup as verbose log) show no error. My app can be build and run correctly.
The designer keep showing a "error" (!) logo on left top corner, with an empty textbox when hovering it.

To check what's going on, I just did a fresh install with all latest version of everything and now the designer just keep failing at load with no error.

**Comment by DMW007** [comment]
For me it helped to run VS as administrator. This has the background that my application developed inside VS requires admin permission. I haven't opened this project on the Windows 10 VM before, but propably the admin requirement has some influence on this issue. Since I'm running VS as administrator, the designer works well.

Still a bit strange, since it just shows the "!" on the top without any message what exactly went wrong, also not in the output window.

**Comment by jhimes144** [comment]
Same problem, has nothing to do with my code. Visual Studio 2022. Running as admin didn't help

**Comment by woodske** [comment]
I ran into this problem too. What fixed it for me was opening the app via the project/solution rather than the folder view. Using Visual Studio 2022 go to File -> Open -> Project/Solution -> click on your myApp.csproj file.

**Comment by mossbee** [comment]
My screen is just like this, anyone can help?
<img width="960" alt="image" src="https://user-images.githubusercontent.com/69780142/209430950-3beb49a4-f24c-4147-8b92-44be634ad3af.png">

**Comment by nigeljm** [comment]
I had this issue and none of the answers solved it. However, just running the project, then stopping it, allowed the designer to load.

**Comment by Ling-YangHui** [comment]
same problem on Visual Studio 2022 17.5

**Comment by dgellow** [comment]
Interesting, I hade the same problem when working on the solution, but as @woodske mentioned opening the csproj directly seems to work.

## When opening by clicking on the sln file

![image](https://user-images.githubusercontent.com/2451004/233617031-a44fdefb-dd4d-4e8d-ad94-e67c7b87322c.png)

## When opening the csproj file

![image](https://user-images.githubusercontent.com/2451004/233617687-fcc42b1d-6bf6-4b11-a851-d6d2eaccd922.png)

**Comment by caotoce** [comment]
Visual studio cannot find your dll. This is because designer doesn't build the application for you (at least the first time round). Just hit build and the red exclamation symbol should go away and designer should pop up. This is why somebody got rid of the problem by running the application (that builds it first).

**Comment by jhimes144** [comment]
I have a very large project built off Avalonia that had been built many
times. The designer only works for custom controls, user controls never
work and I'm always staring at the red exlamation mark. I've just gotten
use to it.

**Comment by dgellow** [comment]
@caotoce Building didn't fix it for me, as I mentioned I instead had to open the csproj directly

**Comment by lugeneu** [comment]
A valid build is required for the designer to be displayed. If you get any error (no matter if it has to do with the designer or anything else) no preview can be shown. At least it was like that in my case.

**Comment by 29654761** [comment]
I solved this problem via remove .vs folder and rebuild all solution.
It caused by I tried to upgrade avalonia base libraries.

**Comment by maxkatz6** [comment]
If anybody has this error again, please open a new issue with the attached logs.

**Comment by sovzzz** [comment]
> If anybody has this error again, please open a new issue with the attached logs.

i kept ran into this problem, how should i generate a log?

**Comment by kevinlau2015** [comment]
vs2022 x86app has the same problem. 
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 

x64 app is Ok.
