### ISSUE TITLE
Intellisense missing all events

### ISSUE THREAD

**Issue by Symbai** [AvaloniaUI/AvaloniaVS#133]
All kind of control events (e.g. `Scroll` on `Scrollbar`) are missing in intellisense. Makes it really difficult porting WPF code to Avalonia. Tested on AvaloniaVS 0.9.0.0 in VS 2019 Community Edition.

**Comment by wdcossey** [comment]
R# also not working

**Comment by ShadowDancer** [comment]
@grokys what do we need for this? Simply pushing all events provided Dnlib to Intellisense will be good starting point?

**Comment by grokys** [comment]
Fixed by #167
