### ISSUE TITLE
Animation previews don't work and cause VS to become very slow

### ISSUE THREAD

**Issue by Deadpikle** [AvaloniaUI/AvaloniaVS#135]
## Dev environment

* Visual Studio on Windows v16.4.6
* Avalonia 0.9.x 

## Bug description

When using animations in a custom control style, Visual Studio slows way down once the preview process has started and loaded. Tab changing is slower, typing has a noticeable delay, and there are other issues. It's...hard to show in a low resolution gif, but as an example, when this is happening, changing caret location via mouse click can take half a second or more. Without this preview open, changing the caret location is instantaneous.

## Repro

1. Download https://github.com/Deadpikle/AvaloniaProgressRing/
2. Open sln
3. Open MainWindow.xaml in the sample
4. Everything (typing, tab changing, etc.) slows way down when the preview loads -- even changing the caret location is slow. Also, the animation doesn't play.

**Comment by grokys** [comment]
We probably should disable animations when running inside the previewer.
