### ISSUE TITLE
Perspex xaml file Custom Tool set after including in project.

### ISSUE THREAD

**Issue by abdelkarim** [AvaloniaUI/AvaloniaVS#14]
If you exclude a perspex xaml and then re-include it, vs will auto set the Custom Tool property, we need to remove it.

![image](https://cloud.githubusercontent.com/assets/1153480/13079140/03a67444-d4c3-11e5-93b9-b696fa777ded.png)

**Comment by ImaBrokeDude** [comment]
https://msdn.microsoft.com/en-us/library/bb166527.aspx

Maybe we still need a different project type too.

**Comment by abdelkarim** [comment]
this is the help I got from the Microsoft/extendvs gitter room:

Initially I was thinking that you could use a priority command target to intercept the command, but if all you want to do is tweak it's CustomTool property after the fact, you could use the EnvDTE's CommandEvents.AfterExecute event handler, look to see if the file in question is a .XAML file with the specific namespace, and then tweak the properties as desired. This old forum post shows how to do this from the context of an addin, but the same scenario would work with a custom package.

https://social.msdn.microsoft.com/Forums/en-US/a4edf8f1-8078-486e-aa44-d377e8cf213d/handle-the-save-event-while-saving-a-build-definition-from-vs2010-toolbar?forum=vsx
