### ISSUE TITLE
xaml editor ignore DesignWidth and DesignHeight

### ISSUE THREAD

**Issue by askovpen** [AvaloniaUI/AvaloniaVS#140]
```xml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:vm="clr-namespace:CoreED.AT.ViewModels;assembly=CoreED.AT"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="CoreED.AT.Views.MainWindow"
        Icon="/Assets/avalonia-logo.ico"
        Title="CoreED.AT">

    <Design.DataContext>
        <vm:MainWindowViewModel/>
    </Design.DataContext>
  <Grid>
    <Grid.ColumnDefinitions>
      <ColumnDefinition Width="200"></ColumnDefinition>
      <ColumnDefinition Width="auto"></ColumnDefinition>
      <ColumnDefinition Width="*"></ColumnDefinition>
    </Grid.ColumnDefinitions>
    <Grid.RowDefinitions>
      <RowDefinition Height="*"></RowDefinition>
      <RowDefinition Height="auto"></RowDefinition>
      <RowDefinition Height="*"></RowDefinition>
    </Grid.RowDefinitions>
    </Grid>
</Window>
```
show small square. all asterisk have 0px width/height in designer.

**Comment by sdb7** [comment]
I am experiencing this as well, this is not happening on previous version (pre 0.9.9 ). I manage to enlarge it by setting minWidth and minHeight

`<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450" 
             x:Class="KresnaGroup.Client.Desktop.Views.ModuleProdukAddView" FontSize="16">

    <Grid Margin="5" ColumnDefinitions="200,1*" RowDefinitions="Auto,Auto,Auto,Auto,Auto, Auto" ShowGridLines="False">

      <StackPanel Orientation="Horizontal" Margin="4" Grid.Row="0" HorizontalAlignment="Right" >
        <Button Margin="0,0,10,0" Command="{Binding Back}" >Back</Button>
        
        <TextBlock Text="Module Penambahan Produk" FontSize="25" FontStyle="Normal" TextAlignment="Center" ></TextBlock>
      </StackPanel>

      <TextBlock Text="Kode Produk" Grid.Row="1" Grid.Column="0" VerticalAlignment="Center" Margin="2"></TextBlock>
      <TextBox Watermark="Masukkan Kode produk dari supplier" Grid.Row="1" Grid.Column="1" Margin="2" Text="{Binding KodeProduk}"></TextBox>

      <TextBlock Text="Nama Produk" Grid.Row="2" Grid.Column="0" VerticalAlignment="Center" Margin="2"></TextBlock>
      <TextBox Watermark="Masukkan Nama produk" Grid.Row="2" Grid.Column="1" Margin="2" Text="{Binding NamaBarang}"></TextBox>

      <TextBlock Text="Deskripsi Produk" Grid.Row="3" Grid.Column="0" VerticalAlignment="Top" Margin="2"></TextBlock>
      <TextBox Watermark="Deskripsi Produk" Grid.Row="3" Grid.Column="1" Margin="2" AcceptsReturn="True" MinHeight="70" Text="{Binding Deskripsi}"></TextBox>

      <TextBlock Text="Deskripsi Klinis" Grid.Row="4" Grid.Column="0" VerticalAlignment="Top" Margin="2"></TextBlock>
      <TextBox Watermark="Deskripsi/Kegunaan secara klinis" Grid.Row="4" Grid.Column="1" Margin="2" AcceptsReturn="True" MinHeight="70" Text="{Binding DeskripsiKlinis}"></TextBox>

      <StackPanel Grid.Row="5" Grid.Column="1" Orientation="Horizontal" Spacing="4" Margin="4, 20,4,4">
        <Button Width="100" Command="{Binding Add}">Simpan</Button>
        <Button Width="100" x:Name="btnCancel" Command="{Binding Cancel}">Batal</Button>

      </StackPanel>

    </Grid>
</UserControl> `

below when i fill with control, it behaved like wrapping the content instead obeying designWidth and designHeight

![data](https://user-images.githubusercontent.com/6058513/80715285-5507a480-8b20-11ea-9854-c4bc7e3250b2.png)

*pardon for my engrish.

**Comment by dmrayt** [comment]
I also have the same problem. The preview is too small or too big when using a DataGrid.

**Comment by rstm-sf** [comment]
https://github.com/AvaloniaUI/Avalonia/pull/4433
