### ISSUE TITLE
Does not open XAML file. Stuck on message "Waiting for IntelliSense to finish initializing..."

### ISSUE THREAD

**Issue by thiago-tota** [AvaloniaUI/AvaloniaVS#142]
When I add a new Avalonia Application project the xaml files do not open.
VS 2019 keep stuck on message "Waiting for IntelliSense to finish initializing...". 
The same behaviour happens if I add a new Avalonia xaml file, Windows or UserControl.

Microsoft Visual Studio Community 2019
Version 16.5.4
Avalonia 0.9.9

![image](https://user-images.githubusercontent.com/30416982/80892665-21697d80-8ccc-11ea-86f1-d8e5fa6b512d.png)

**Comment by Carlos487** [comment]
I am experimenting this too. As a workaround I usually close the file tab and open it again for it to works

**Comment by Gillibald** [comment]
But then you just get the XML editor without IntelliSense right?

**Comment by Carlos487** [comment]
I actually tried and I got IntelliSense suggestions. Maybe another plugin might be causing the conflict.

**Comment by grokys** [comment]
Just came across this. Exception is:

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=AvaloniaVS
  StackTrace:
   at AvaloniaVS.Services.EditorFactory.CreateEditorControl(IVsTextLines bufferAdapter) in D:\projects\AvaloniaUI\AvaloniaVS\AvaloniaVS\Services\EditorFactory.cs:line 189
```

`buffer` is being returned as `null`.

**Comment by grokys** [comment]
So yeah, looks like a recent update to VS broke this: a bunch of methods we relied on now return null while VS is initializing intellisense as far as I can see. Of course all this stuff is undocumented, so I'm having a real hard time figuring out how to fix it.

**Comment by grokys** [comment]
Actually I get this occasionally opening a C# file in VS 16.6 so I suspect it's a VS bug.

**Comment by kaddourDjakam** [comment]
same problem fixed it by just remove the .vs file in the main project directory
