### ISSUE TITLE
"Invalid Markup" in VS designer when project contains spaces

### ISSUE THREAD

**Issue by Urriellu** [AvaloniaUI/AvaloniaVS#144]
How to replicate:
- Create a new Avalonia MVVM Project.
- The name of the project must contain a space. E.g: "My Project".
- Open MainWindow.xaml with Visual Studio in designer mode.
- Designer displays: "Invalid Markup - Check the Error List for more information".
- Error List says "Unable to resolve type MainWindowViewModel from namespace clr-namespace:My_Project.ViewModels;assembly=My_Project".

Reason:
- Visual Studio compiles and creates assemblies "My Project.dll" and "My Project.exe", but Avalonia designer is tying to load "My_Project.dll/exe" instead.
- Considering that "My Project.dll/exe" are valid files, I would say this is a bug in Avalonia designer.

How to manually resolve/hack:
- Open "My Project" project properties and change "Assembly name" from "My Project" to "My_Project". This will compile into "My_Project.dll/exe" and Avalonia designer will find it correctly.

**Comment by prashantvc** [comment]
I am not able reproduce this with the extension version 11.1
Please reopen the issue if you continue to see an error
