### ISSUE TITLE
Visual Studio 2019 version 16.6.0 update: broken UserControl template

### ISSUE THREAD

**Issue by frederik-hoeft** [AvaloniaUI/AvaloniaVS#149]
After updating to Visual Studio 2019 Enterprise version 16.6.0 I seem unable to create new User Controls using the templates from the "Add New Item" menu (using the MVVM Application version, did not test the other one). I also reinstalled the Avalonia extension via the market place - the problem persists.

It seems to create the "UserControl1.xaml" file, as can be seen in the windows explorer but then errors out with the following message:
 
<img width="528" alt="error1" src="https://user-images.githubusercontent.com/43813142/82705984-f6de6500-9c78-11ea-8a38-97f42a42fc45.png">

Interestingly enough there seem to be two entries now in the "Add New Item" menu as can be seen below:

<img width="724" alt="error2" src="https://user-images.githubusercontent.com/43813142/82706271-884dd700-9c79-11ea-828d-59dce60bb854.png">

As this wasn't a problem either before I installed the update I am guessing it may have broken the Avalonia extension? 

However I didn't try this on a different PC, so it could be just my VS installation being messed up.

**Comment by grokys** [comment]
Move to repository for VS extension.

**Comment by wafflecomposite** [comment]
Same issue on VS 16.6.0

**Comment by aaechoman** [comment]
I have to some issue on VS 16.6.0.

**Comment by grokys** [comment]
Could you check if this was fixed by the 0.9.10.0 version of the extension?

**Comment by frederik-hoeft** [comment]
Technically it has been fixed but also introduced a new issue. First of all: Now it does generate the `UserControl.xaml` and `UserControl.xaml.cs` files as intended and the weird item duplication in the New Item Wizard is gone as well. 

However:
After the wizard finishes only the `UserControl.xaml.cs` file is visible in the Solution Explorer as can be seen below (ignore the other control in there):
<img width="328" alt="1" src="https://user-images.githubusercontent.com/43813142/83862827-c25fb400-a722-11ea-8c91-17e4c283227f.png">

Taking a look at the `.csproj` file it now seems to use the `<Page></Page>` tags
<img width="696" alt="2" src="https://user-images.githubusercontent.com/43813142/83863033-0bb00380-a723-11ea-8c59-71ccb72d67fc.png">

Changing this to the `<EmbeddedResource></EmbeddedResource>` tags like this
<img width="765" alt="3" src="https://user-images.githubusercontent.com/43813142/83863176-474acd80-a723-11ea-83c6-e5e84522d563.png">

fixes the issue and makes the `UserControl.xaml` file show up in the Solution Explorer too.
<img width="273" alt="4" src="https://user-images.githubusercontent.com/43813142/83863351-84af5b00-a723-11ea-8734-cca2583a4f9e.png">

A quick project reload then merges these two files together to one item in the Solution Explorer as we're used to.

So while this issue could technically be closed, the workflow still doesn't feel as smooth as it was before the Visual Studio update
