### ISSUE TITLE
Value does not fall within the expected range.

### ISSUE THREAD

**Issue by microhobby** [AvaloniaUI/AvaloniaVS#152]
First time to open a solution, that has .xaml files previously open, I get the follow error:

```
An error occurred in 'TorizonAvaloniaSample' while attempting to open 'AboutView.xaml'
Value does not fall within the expected range.
```

![image](https://user-images.githubusercontent.com/2633321/82963160-7ed5af00-9f98-11ea-80c8-91d4f81e4b59.png)

And if I close and reopen it works without problems.

Extension version: 
![image](https://user-images.githubusercontent.com/2633321/82963202-99a82380-9f98-11ea-8e76-654680aceedf.png)

Let me know if there is any more information that may be useful. Thanks!

**Comment by grokys** [comment]
Huh, strange: from what I can see this doesn't seem to be caused by our extension, it looks to be something going wrong in VS itself. Does this happen often?

**Comment by microhobby** [comment]
@grokys yes, I confirm that almost every time I open a solution where I left `.xaml` files open previously
