### ISSUE TITLE
Error on Fresh Build - Exception caught by FireAndForget

### ISSUE THREAD

**Issue by valkyrienyanko** [AvaloniaUI/AvaloniaVS#156]
Running on Visual Studio Community 2017

## Steps to Reproduce
1. Create a new MVVM Avalonia application
2. Change target framework to 2.1
3. Build
4. Error seen in output from Avalonia Diagnostics

```
17:01:38.246 [Error]  Exception caught by FireAndForget
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at AvaloniaVS.Services.PreviewerProcess.<OnMessageAsync>d__37.MoveNext() in D:\a\1\s\AvaloniaVS\Services\PreviewerProcess.cs:line 433
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at AvaloniaVS.Services.PreviewerProcess.<OnMessageAsync>d__37.MoveNext() in D:\a\1\s\AvaloniaVS\Services\PreviewerProcess.cs:line 433<---
```

**Comment by grokys** [comment]
Just tried to repro this on my machine and everything worked as expected. I wonder what's not working on your system?

In addition the line where the NRE is being reported is simply calling `_log.Error` and afaics all null checks are being done. Just to check, which version of the Avalonia VS extension are you using?

**Comment by grokys** [comment]
Actually, this issue seems to be the same thing https://github.com/AvaloniaUI/AvaloniaVS/issues/154#issuecomment-636382950 and there's it's stated `Avalonia VS Extension 0.9.10 from VS marketplace`.

Going to close this issue and track the error in #154.
