### ISSUE TITLE
VS opening Avalonia XAML in WPF designer

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/AvaloniaVS#159]
This is a strange one. Visual Studio sometimes opens Avalonia XAML files in the WPF designer, however deleting the file, recreating and then undoing the changes to the file results in VS opening the correct designer! There seems to be some hidden state somewhere this is getting set up wrong:

- Clone https://github.com/Splitwirez/AvaloniaRibbon
- Checkout `72e546048d2922a0d0024fcdd9a9bb57a65bd01c`
- Open AvaloniaRibbon.sln in VS
- Open `Views\MainWindow.xaml` - **VS opens the WPF designer instead of the Avalonia designer**
- Delete `MainWindow.xaml`/`MainWindow.xaml.cs`
- On `Views` folder, click Add -> New Item -> Avalonia -> Window and add a new window called `MainWindow` to replace the one just deleted
- (Delete the cruft that VS erroneously adds to the .csproj)
- Open `MainWindow.xaml` again - **VS opens the Avalonia designer, hooray!**
- Undo the changes to `MainWindow.xaml`/`MainWindow.xaml.cs` to revert back to the state after checkout
- Open `MainWindow.xaml` again - VS **still** opens the Avalonia designer, even though it's the same code that originally caused the WPF designer to open

**Comment by maxkatz6** [comment]
Note: it's recommended to use "axaml" file format, which is the default right now in all templates. There is no such issue with "axaml" files.

**Comment by MikeCodesDotNET** [comment]
I did some digging into this years ago and even had calls with the VS Team to discuss it. The consensus from the VS Team was that Microsoft 'owns' the XAML file extension, and we should use something else. 

For that reason, we went with .axaml.
