### ISSUE TITLE
Allow Designer to render Xaml when not wrapped in a suitable root.

### ISSUE THREAD

**Issue by ghost** [AvaloniaUI/AvaloniaVS#17]
Originally by @danwalmsley 

> i.e.
> 
> ```
> <TabItem xmlns="https://github.com/perspex" Header="Type">
>   <DropDown Items="{Binding ProjectTypeOptions}" SelectedItem="{Binding ProjectType, Mode=TwoWay}" />
> </TabItem>
> ```
> 
> Above could be rendered if Designer wrapped it in a Presenter.. currently it doesn't.

**Comment by ImaBrokeDude** [comment]
Latest Designer has this feature but testing is still needed.
