### ISSUE TITLE
XAML syntax highlighting and autocomplete suggestions are lacking in comparison to vanilla WPF

### ISSUE THREAD

**Issue by derekantrican** [AvaloniaUI/AvaloniaVS#173]
Here a comparison of syntax highlighting and autocomplete suggestions writing the same code between Avalonia and WPF:

WPF:
![](https://i.imgur.com/5HxGq0t.gif)

Avalonia:
![](https://i.imgur.com/voeCx6U.gif)

Especially when setting the Binding, Avalonia is lacking any sort of autocomplete suggestions

**Comment by grokys** [comment]
Transferred to Avalonia VS extension repository.

**Comment by unofficialdev** [comment]
hope this can be improved soon

**Comment by jmacato** [comment]
I could suggest you folks to use Rider instead. Avalonia support there (autocomplete and intellisense) are top-notch there :)

**Comment by maxkatz6** [comment]
There were made multiple improvements. It still might be lacking in some places (like, bindings autocompletion), but I would ask to create separate issues per each.

**Comment by pmankow** [comment]
Please revisit this.
