### ISSUE TITLE
F# templates

### ISSUE THREAD

**Issue by FoggyFinder** [AvaloniaUI/AvaloniaVS#174]
Would be awesome to have. Currently it's inconvenient especially when it's come to adding new UserControl/Window

**Comment by grokys** [comment]
If someone wants to submit a PR with F# templates and someone else wants to review them, I'd be 👍 with including! Unfortunately I don't know F# well enough to feel confident doing this myself.

**Comment by FoggyFinder** [comment]
Awesome. I know a very little about VS templates but it shouldn't be too complicated. I'll try to create PR on weekend
