### ISSUE TITLE
does not work with TargetFramework net5.0

### ISSUE THREAD

**Issue by cyungmann** [AvaloniaUI/AvaloniaVS#176]
The extension does not seem to work when specifying `<TargetFramework>net5.0</TargetFramework>`. I get "No executable found" on the designer surface and "No Executable" / "Reference the library from an executable or wait for the solution to finish loading.". The issue seems to be in `AvalonaVS.Views.AvaloniaDesigner.LoadTargetsAsync` > `IsValidOutput` > `AvaloniaVS.Models.ProjectOutputInfo.IsNetCore`, which is implemented as follows:

```csharp
public bool IsNetCore => TargetFramework?.StartsWith("netcoreapp") ?? false;
```

**Comment by cyungmann** [comment]
Whoops, I found that it works if I specify `<TargetFramework>netcoreapp5.0</TargetFramework>`. IIUC, these are supposed to be treated basically equivalently though.

**Comment by rstm-sf** [comment]
Hi, changes in #181  should fix the behavior
