### ISSUE TITLE
"using:" support

### ISSUE THREAD

**Issue by maxkatz6** [AvaloniaUI/AvaloniaVS#178]
With latest preview Avalonia now supports "using:" syntax.
But it seems VS plugin doesn't know about it and need to be updated.
https://github.com/AvaloniaUI/Avalonia/issues/4417

**Comment by donandren** [comment]
once `using:` is supported by [Avalonia.Ide](https://github.com/kekekeks/Avalonia.Ide) it will be available for the VS plug, with just an submodule update
