### ISSUE TITLE
d:DesignWidth and d:DesignHeight not working in the designer

### ISSUE THREAD

**Issue by Shayan-To** [AvaloniaUI/AvaloniaVS#182]
`Width`, `Height`, and `d:DataContext` work perfectly well, but `d:DesignWidth` and `d:DesignHeight` are not working in the designer. It works as if no width or height is set.

![image](https://user-images.githubusercontent.com/12458563/98631362-80bae100-2332-11eb-8ce4-f362001b8e6b.png)

**Comment by rstm-sf** [comment]
This has already been fixed and is waiting for a backport https://github.com/AvaloniaUI/Avalonia/pull/4433

**Comment by a44281071** [comment]
This attributes is obsolete. In WPF, we can use d:Height or d:Width and all other attributes: add letters at the beginning of a attribute.
