### ISSUE TITLE
Previewer is using a non-standard ApplicationLifetime, causing it to crash if the code doesn't check

### ISSUE THREAD

**Issue by MasterMann** [AvaloniaUI/AvaloniaVS#189]
In summary, if you're using the Application class in a non-standard way (modifying the `OnFrameworkInitializationCompleted` function, etc.) and there is no check for `ApplicationLifetime == IClassicDesktopStyleApplicationLifetime`, it will cause a previewer crash.

Took a long time to figure this out.
I think this should be added to the Wiki, it's currently not clear enough how to separate design-time and normal initialization, simple Design.IsInDesignMode didn't work as well.

**Comment by Gillibald** [comment]
Not safe casting the lifetime is an error on your side and totally expected. This is the intended behavior.

**Comment by MasterMann** [comment]
Seems like I'm also having different issues where a viewmodel requires a class singleton. Since previewer doesn't create it - it causes a NullReferenceException, basically requiring to set up a design-time stub for every viewmodel.
