### ISSUE TITLE
Norton Heuristik Warning

### ISSUE THREAD

**Issue by KarlM31** [AvaloniaUI/AvaloniaVS#194]
Hello,
after compiling Avalonia 0.10 (VS 2019-Win10) Template, i get the message 
Heur.AdvML.B Heuristik Virus Warning from Norton 360 for the ProjectName.dll

if i compile the Template with the Default Name AvaloniaApplication1
i get no error....

each other name i get the warning...

GData works without any warnings..

THANKS in advance
bye
karl

**Comment by maxkatz6** [comment]
Probably Norton doesn't like not code signed applications, assuming your application can be from untrusted sources. Even if it's weird. 

Or maybe do you have any logs, warning messages, that can provide some additional context?

**Comment by KarlM31** [comment]
i used the norton submission portal to inform norton for the incorrectly heuristic warning....

still waiting.....
