### ISSUE TITLE
Previewer doesn't Support Targeting "net5.0" only "netcoreappX"

### ISSUE THREAD

**Issue by lunarcloud** [AvaloniaUI/AvaloniaVS#198]
Tested with both 0.9.12 and 0.10.0

If your project targets "netcoreapp3.1" or "netcoreapp5.0" and build, the previewer works.
If you switch to "net5.0" it works... *until you clean* (I cleaned solution). 
Then it fails to work.

Build and actual run works fine.

**Comment by maxkatz6** [comment]
You most likely need to update your plugin. This issue was fixed already before.

**Comment by lunarcloud** [comment]
I'll test it a bit. I think I was only testing the different versions by the nuget manager.

**Comment by lunarcloud** [comment]
Yes, it works with a new avalonia project. I was avoiding mixing different versions of plugin and nuget packages and didn't want to migrate the breaking changes of my app.

This is, as you say, no longer an issue.
