### ISSUE TITLE
How to enable output full stack trace listing caught design time exception

### ISSUE THREAD

**Issue by kekyo** [AvaloniaUI/AvaloniaVS#201]
Hi, I'm debugging my own project library based Avalonia. I saw caught exception on VSext design time diag message like:

```
11:32:12.621 [Debug] 22824 <= StartDesignerSessionMessage { SessionId: "e5fa92b5-b94a-4e67-9b84-95fd259…" }
11:32:12.622 [Verbose] 22824 Finished PreviewerProcess.OnMessageAsync()
11:32:12.842 [Verbose] 22824 Started PreviewerProcess.OnMessageAsync()
11:32:12.843 [Debug] 22824 <= UpdateXamlResultMessage { Error: "System.InvalidOperationExceptio…", Handle: null, Exception: ExceptionDetails { ExceptionType: "InvalidOperationException", Message: "Collection was modified; enumer…", LineNumber: null, LinePosition: null } }
11:32:12.847 [Error] 22824 UpdateXamlResult error
System.Xaml.XamlException: Collection was modified; enumeration operation may not execute.
11:32:12.850 [Verbose] 22824 Finished PreviewerProcess.OnMessageAsync()
11:32:13.111 [Verbose]  Finished AvaloniaDesigner.CreateCompletionMetadataAsync() took 00:00:02.3061883 for "C:\PROJECT\Epoxy\samples.FSharp\EpoxyHello.Avalonia\EpoxyHello.Avalonia.Desktop\bin\Debug\net5.0\EpoxyHello.Avalonia.Desktop.dll"
11:32:13.111 [Verbose]  Finished AvaloniaDesigner.CreateCompletionMetadataAsync()
```

It's suppressed InvalidOperationException message without any stack trace. Can I enable it? How to do it? Or other options?

**Comment by blue00** [comment]
Not sure if this is helpfull, but just FYI:

I tried to reproduce this problem with the current master branch. But for me there is no limitation to 32 chars per log value when a UpdateXamlResult error is received:

21:36:04.579 [Information] 0 Starting previewer process for '"C:\Users\abc\source\repos\AvaloniaApplication1.Desktop\bin\Debug\net7.0\AvaloniaApplication1.Desktop.dll"'
21:36:04.584 [Information] 20524 Started previewer process for '"C:\Users\abc\source\repos\AvaloniaApplication1.Desktop\bin\Debug\net7.0\AvaloniaApplication1.Desktop.dll"'. Waiting for connection to be initialized.
21:36:04.651 [Information] 20524 Connection initialized
21:36:05.047 [Error] 20524 UpdateXamlResult error
**System.Xaml.XamlException: Test exception message aaaaa aaaaa bbbbb bbbbb aaaaa aaaaa bbbbb bbbbb.**

Maybe you could try if this LoggerConfiguration has something to do with it?
https://github.com/AvaloniaUI/AvaloniaVS/blob/283a55705dc2c0f8744d46f1ed4010ef1b268473/AvaloniaVS.Shared/Services/PreviewerProcess.cs#L43-L48

**Comment by kekyo** [comment]
@blue00 Thank you for your information!

Okay, it seems to me that this is because the length is hard-coded and cannot currently be changed.
If I had the luxury, I would like to be able to manipulate this from configuration.

This is very helpful, as I was unable to find the relevant code for this issue. Thank you!
