### ISSUE TITLE
F# templates: xaml instead of axaml

### ISSUE THREAD

**Issue by hhfranzo** [AvaloniaUI/AvaloniaVS#202]
Hi,

I noticed that the extensions of the xaml file is actually xaml in F# templates while in C# templates is axaml.
Is that correct?

Cheers,
Mauro

**Comment by FoggyFinder** [comment]
From my experience .axaml files don't work well in F# projects.
Unsure what's a current status since I didn't have much opportunities to work with Avalonia and F# lately.
