### ISSUE TITLE
Previewer 100% CPU usage

### ISSUE THREAD

**Issue by PieroCastillo** [AvaloniaUI/AvaloniaVS#203]
I don't know what's happen...  Just I updated VS to the last estable version...

![image](https://user-images.githubusercontent.com/39932324/111727798-98065f80-8839-11eb-95be-9535061f9042.png)

Settings:
- Windows 10 20H2
- Avalonia 0.10 stable
- AvaloniaVS 0.10 stable
- Net 5.0 stable
- Visual Studio 16.9.2 (the old version what I used is 16.8)

**Comment by maxkatz6** [comment]
Are you sure, that it's not caused by your code, which is executed by previewer?
I don't see same issue, although I am using VS preview usually.

**Comment by MikeCodesDotNET** [comment]
I also can't reproduce the issue here with the latest stable build. 

I'm leaning towards its something funky happening with the AudioPlayer control.

**Comment by PieroCastillo** [comment]
Sorry, the error is of the lib, I'll close this issue
