### ISSUE TITLE
Support Visual Studio 2022

### ISSUE THREAD

**Issue by MikeCodesDotNET** [AvaloniaUI/AvaloniaVS#206]
As per the title. We need to add support for VS22. 

I've already got a local branch with it working and it was pretty straight forward to upgrade. No code changes were required!

**Comment by MikeCodesDotNET** [comment]
I've commited https://github.com/AvaloniaUI/AvaloniaVS/commit/d2e3888e6dedf3d5fa234c56044ac56afebc4043 which enables support for the 17.0.0 Preview 1.0 [31408.342.d17.0]. I believe my version in an internal build, so the changes will need to be checked on the public preview release.

**Comment by maxkatz6** [comment]
@MikeCodesDotNET it seems "[17.0.0-previews-1-31410-273](https://www.nuget.org/packages/Microsoft.VisualStudio.SDK/17.0.0-previews-1-31410-273)" is in public preview

**Comment by 0x90d** [comment]
Any update?

**Comment by stesmi** [comment]
I cloned the repo and updated references and I have something running. I have not tested it extensively yet, but right now I have ReSharper and Avalonia running in VS 2022 preview 3.

My changes were way bigger than Mike's, though, and I haven't checked how many of the updates are actually necessary.
Hopefully we can get an official release soon.

**Comment by grokys** [comment]
I've been looking into this for VS 2022 Preview 3.1 and our use of the DTE seems to be causing problems, looks like we need to replace our usage of that with something more modern.

I've not spent much time on it so far but I've opened a branch at https://github.com/AvaloniaUI/AvaloniaVS/tree/update/vs-2022 with my progress so far.

As an aside, should we drop support for < VS2019? I don't have VS2017 installed on my machine any more to test with.

**Comment by uberhalit** [comment]
As final VS2022 released now, I'd be great if we can get an official fox soon.

**Comment by jonfast565** [comment]
Really interested in seeing a fix for this soon!

**Comment by grokys** [comment]
@uberhalit @jonfast565 we have an installer which works in #223, and you can already download an installer from our CI (https://dev.azure.com/AvaloniaUI/AvaloniaUI/_build/results?buildId=16490&view=artifacts&pathAsName=false&type=publishedArtifacts).

The remaining problem is to get this working on earlier versions too.

Related: https://github.com/AvaloniaUI/Avalonia/issues/6927

**Comment by alexhelms** [comment]
I just downloaded the artifact from here https://dev.azure.com/AvaloniaUI/AvaloniaUI/_build/results?buildId=16726&view=results and I am unable to install it. I am running VS2022 17.0.2 on Windows 11. Below is the log from the VSIX installer.


```
12/4/2021 12:40:06 PM - Microsoft VSIX Installer
12/4/2021 12:40:06 PM - -------------------------------------------
12/4/2021 12:40:06 PM - Initializing Install...
12/4/2021 12:40:06 PM - Extension Details...
12/4/2021 12:40:06 PM - 	Identifier      : AvaloniaForVisualStudio
12/4/2021 12:40:06 PM - 	Name            : Avalonia for Visual Studio
12/4/2021 12:40:06 PM - 	Author          : Avalonia UI
12/4/2021 12:40:06 PM - 	Version         : 0.10.10.0
12/4/2021 12:40:06 PM - 	Description     : Previewer and templates for Avalonia applications and libraries.
12/4/2021 12:40:06 PM - 	Locale          : en-US
12/4/2021 12:40:06 PM - 	MoreInfoURL     : 
12/4/2021 12:40:06 PM - 	InstalledByMSI  : False
12/4/2021 12:40:06 PM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
12/4/2021 12:40:06 PM - 
12/4/2021 12:40:06 PM - 	Supported Products : 
12/4/2021 12:40:06 PM - 		Microsoft.VisualStudio.Community
12/4/2021 12:40:06 PM - 			Version : [15.0,17.0)
12/4/2021 12:40:06 PM - 		Microsoft.VisualStudio.Community
12/4/2021 12:40:06 PM - 			Version : [17.0,18.0)
12/4/2021 12:40:06 PM - 
12/4/2021 12:40:06 PM - 	References      : 
12/4/2021 12:40:06 PM - 
12/4/2021 12:40:06 PM - Searching for applicable products...
12/4/2021 12:40:06 PM - Found installed product - Global Location
12/4/2021 12:40:06 PM - Found installed product - AtmelStudio
12/4/2021 12:40:06 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

```

**Comment by davidbuckleyni** [comment]
Any Update on this tried to install today on VS2022 and says the extension is not comptable?

**Comment by kekekeks** [comment]
Due to breaking changes in VS2022 there are now separate extensions:
https://marketplace.visualstudio.com/items?itemName=AvaloniaTeam.AvaloniaVS - 2022
https://marketplace.visualstudio.com/items?itemName=AvaloniaTeam.AvaloniaforVisualStudio 2017, 2019
