### ISSUE TITLE
Selecting controls in designer is offset

### ISSUE THREAD

**Issue by derekantrican** [AvaloniaUI/AvaloniaVS#209]
**Describe the bug**
Screen recording:
![](https://i.imgur.com/Zmy3byM.gif)

*I think this could be due to DPI scaling. I have the "Change the size of text, apps, and other items" display setting set to 175%*

**To Reproduce**

1. Add a few controls to a window
2. Try clicking on different ones in the designer
3. Note that you cannot select the control by clicking directly on it, but must click off to the right (or below the control in some cases)
*If you have trouble reproducing this, try changing the "Change the size of text, apps, and other items" Windows display setting (which may require a restart/relogin/etc to see effects)*

**Expected behavior**
Should be able to click on the actual tab to select it

**Desktop (please complete the following information):**

- OS: Windows 10
- Version: 0.10.6
- VS extension: 0.10.3.0

**Comment by derekantrican** [comment]
Ah, you're right. I'll update the issue accordingly

**Comment by maxkatz6** [comment]
Pretty sure it was fixed at some point. Can't reproduce anymore.
