### ISSUE TITLE
Add support back in for Paml users for limited time with some kind of notification

### ISSUE THREAD

**Issue by ghost** [AvaloniaUI/AvaloniaVS#21]
I think since we did transition back to xaml, we still should allow the extension to work with paml file for a limited time to make transitioning a little easier for some users.

**Comment by ImaBrokeDude** [comment]
I think this should be our next priority if possible.

**Comment by abdelkarim** [comment]
I am working on a PR.

**Comment by ImaBrokeDude** [comment]
Okay so Paml support is back in, we just need to add a notification somewhere. Something like "Perspex is changing! Please convert you .paml files to .xaml. For more information see <link to doc with more info on the mogration>. Then we meed a doc for the link.

Basically:

* Notification that shows until a user closes and doesnt show again.
* Doc explaining the mogration (Why and how)
* Possibly even a migration tool (for example I had to modify the file name and project file outside of VS for class libraries... the nested file's name was locked)
