### ISSUE TITLE
VS2017: "prerequisites that cannot be resolved"

### ISSUE THREAD

**Issue by FerGT50** [AvaloniaUI/AvaloniaVS#211]
**Describe the bug**
Can't install (current) Avalonia extension on Visual Studio 2017 Community Edition

**To Reproduce**
1. Download extension
2. Select "Open with" "VisualStudio.Launcher.vsix" 
3. Error: "The extension can't be installed because of prerequisites that cannot be resolved"

**Expected behavior**
Correctly installed extension

**Desktop (please complete the following information):**

- OS: Windows 10 Professional 64 bit
- Version 21H1 (19043.1202)

**Additional context**
Which are, exactly, the prerequisites for Visual Studio 2017? Which packages are needed besides the obvious C++/C#/.net devkits and Windows SDK?
![avalonia_error1](https://user-images.githubusercontent.com/68430253/132545717-c2fda12f-eab1-47a1-a209-0636f0a3ba48.png)

**Comment by grokys** [comment]
Strange, the only prerequisites we require should all be installed if you have the C# workload installed:

https://github.com/AvaloniaUI/AvaloniaVS/blob/master/AvaloniaVS/source.extension.vsixmanifest#L13-L15

Is this particular to this VS instance on this machine or are you seeing it on other machines too?

**Comment by grokys** [comment]
As an aside: what are the reasons for still using VS2017? I was thinking of dropping support for VS2017 soon as I no longer have it on my machine to test with.

**Comment by FerGT50** [comment]
No plans to switch to VS2019 in the immediate future: will jump to 2022 directly.
I have only this installation of VS2017 to work with; I develop on Linux usually.
Complete infos, in case it helps:

`Microsoft Visual Studio Community 2017 
Version 15.9.38
VisualStudio.15.Release/15.9.38+28307.1622
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2017   00369-60000-00001-AA546
Microsoft Visual C++ 2017

Arduino IDE for Visual Studio by Visual Micro   19.0
Visual Micro is an Arduino Compatible IDE for Visual Studio 2017-2019. For more information and forum please visit www.visualmicro.com.

ASP.NET and Web Tools 2017   15.9.04012.0
ASP.NET and Web Tools 2017

C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

MLGen Package Extension   1.0
MLGen Package Visual Studio Extension Detailed Info

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Visual Basic Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake`

**Comment by jimsungi** [comment]
I got same problem.
Further I can attach logs.

![image](https://user-images.githubusercontent.com/16549235/209271712-f7f5cedf-45ea-42eb-8ee7-3e92fcb22d0e.png)

[dd_VSIXInstaller_20221223133458_0d7c.log](https://github.com/AvaloniaUI/AvaloniaVS/files/10292089/dd_VSIXInstaller_20221223133458_0d7c.log)
