### ISSUE TITLE
.Net Host Stop Working.

### ISSUE THREAD

**Issue by Gao996** [AvaloniaUI/AvaloniaVS#219]
This error will be reported every time you click .axaml.

Look here : [#155](https://github.com/AvaloniaUI/AvaloniaVS/issues/155)

Thanks!

**Comment by Takoooooo** [comment]
Hey! Do you have a consistent repro to let us debug your issue?

**Comment by Gao996** [comment]
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly

**Comment by Gao996** [comment]
16:53:39.344 [Error] 19024 <= "   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)"
16:53:39.344 [Error] 19024 <= "   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)"
16:53:39.344 [Error] 19024 <= "   at System.Reflection.Assembly.LoadFile(String path)"
16:53:39.345 [Error] 19024 <= "   at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.Main(String[] cmdline) in /_/src/Avalonia.DesignerSupport/Remote/RemoteDesignerEntryPoint.cs:line 167"
16:53:39.345 [Error] 19024 <= "   at Avalonia.Designer.HostApp.Program.Main(String[] args) in /_/src/tools/Avalonia.Designer.HostApp/Program.cs:line 47"
