### ISSUE TITLE
When you open a axaml\xaml file in VS with this extension it will appear in VS git as changed

### ISSUE THREAD

**Issue by Takoooooo** [AvaloniaUI/AvaloniaVS#220]
It is really annoying.
https://recordit.co/fhSqN5BMUb
When you close the tab it will be removed from the list of the changes.

**Comment by scottdoingwork** [comment]
I think the reason is that calling GetDocData with setting value 1 to parameter fEnsureWritable. Following code is in file AvaloniaVS\Services\EditorFactory.cs.
ErrorHandler.ThrowOnFailure(invisibleEditor.GetDocData(
                    fEnsureWritable: 1,
                    riid: ref guidIVSTextLines,
                    ppDocData: out var docDataPointer));

**Comment by Takoooooo** [comment]
@scottdoingwork yeah, setting fEnsureWritable to 0 fixes the problem for me on vs2019,on vs2022 this problem doesn't seem to appear,btw I am not familiar with this code so I am not sure whether we should change it or not.
