### ISSUE TITLE
Does not install on Visual Studio 2022

### ISSUE THREAD

**Issue by Ryhon0** [AvaloniaUI/AvaloniaVS#222]
Searching for the extension in the IDE doesn't return it, attempting to install it by downloading a .vsix throws the `VSIXInstaller.NoApplicableSKUsException` exception. Here's the installer log: [dd_VSIXInstaller_20211105135926_22cc.log](https://github.com/AvaloniaUI/AvaloniaVS/files/7486143/dd_VSIXInstaller_20211105135926_22cc.log)

**Comment by GaNacereddine** [comment]
with the release of vs 2022 it would be really good if we have an update on this as .net 6 is not supported on vs 2019

**Comment by timunie** [comment]
I learned yesterday on gitter that there is an option to install the extension is VS 2022 and wanted to share this here: 

You can download a preview version from here
https://dev.azure.com/AvaloniaUI/AvaloniaUI/_build/results?buildId=16726&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by colejohnson66** [comment]
See #206. VS 2022 support is not complete

**Comment by maxkatz6** [comment]
Duplicate
