### ISSUE TITLE
Will this project/extension support Visual Studio 2022 (preview for now) for macOS?

### ISSUE THREAD

**Issue by arloan** [AvaloniaUI/AvaloniaVS#241]
I downloaded the vs extension for vs2022, while vs2022 preview 7 for macOS does not recognize .vsix file.

**Comment by MikeCodesDotNET** [comment]
Visual Studio for Mac uses a very different extension architecture. We do have a plugin for VS4Mac in development, but we're not sure when it'll be ready.

**Comment by chatterzhao** [comment]
how to get vs4mac?
