### ISSUE TITLE
UserControl child controls not being initialized

### ISSUE THREAD

**Issue by jack-the-cat** [AvaloniaUI/AvaloniaVS#249]
When creating a UserControl, the child controls are all "null" when compiled and run
![image](https://user-images.githubusercontent.com/10653980/163679808-c7c587d6-6efa-4400-9797-e7ffab813f2a.png)

Not sure if I'm missing something obvious. The main window control correctly initializes all it's child controls, but for some reason the UserControl does not. 

Steps to Reproduce:
1. Created an Avalonia UI project
2. Added some built-in controls to the MainWindow
3. Added a UserControl via Add -> New Item... -> Avalonia -> User Control (Avalonia)
4. Added some built-in controls to the UserControl
5. Added some code behind the UserControl, specifically to update a value if the users scrolls the mouse wheel over the control
6. Added the new UserControl to MainWindow
7. Compile and run
8. Got the above NullReferenceException when trying to update a TextBlock on the UserControl
9. Discovered all of the UserControl's child controls were null

The UserControl XAML:
![image](https://user-images.githubusercontent.com/10653980/163680076-bc586ec2-5034-4a46-bcc9-d23ce3fb2eed.png)

The MainWindow XAML:
![image](https://user-images.githubusercontent.com/10653980/163680120-0052fbfd-e3e6-4734-8dba-cdd6ed3acc1f.png)

The UserControl Code Behind:
![image](https://user-images.githubusercontent.com/10653980/163680134-356c0a25-7845-42e9-9de9-5deff127f166.png)

Environment:
Windows 10 x64, Visual Studio 2022 Preview Version 17.2.0 Preview 2.1
.NET 6, Avalonia NuGet packages: Avalonia, Avalonia.Desktop, Avalonia.Diagnostics version 0.10.13, XamlNamespaceReferenceGenerator 1.3.4
Avalonia for Visual Studio 2022 extension, version 0.10.12

**Comment by Takoooooo** [comment]
Moving it to avaloniavs because it seems that we need to update our templates in vs plugin

**Comment by Takoooooo** [comment]
Before i will do that please use just our cli templates,they are correct

**Comment by maxkatz6** [comment]
I don't see any bugs here. It seems like [XamlNameReferenceGenerator](https://github.com/AvaloniaUI/Avalonia.NameGenerator) was used together with old Avalonia templates. It resulted in a conflict of InitializeComponent methods. Locally defined one hides another from the source generator.

**Comment by jack-the-cat** [comment]
I'm using the ones that come with the extension (I think, I've not installed any myself manually, not even sure how I'd go about doing that)

**Comment by maxkatz6** [comment]
Basically, if you have XamlNameReferenceGenerator used, you need to have "partial" keyword on your user control and there shouldn't be InitializeComponent defined.

**Comment by maxkatz6** [comment]
Window tempaltes in this repo seems to be fine 
https://github.com/AvaloniaUI/AvaloniaVS/blob/master/templates/AvaloniaMvvmApplicationTemplate/Views/MainWindow.axaml.cs

But UserControl template still has InitializeComponent
https://github.com/AvaloniaUI/AvaloniaVS/blob/master/templates/AvaloniaUserControlTemplate/UserControl.axaml.cs

"dotnet templates" doesn't have this problem though
https://github.com/AvaloniaUI/avalonia-dotnet-templates/blob/master/templates/csharp/usercontrol/NewUserControl.axaml.cs

**Comment by jack-the-cat** [comment]
I'd suggest the template needs tweaking, although at the moment I'm working around it by deleting the InitializeComponent() function body in the UserControls I'm creating through Visual Studio.

**Comment by maxkatz6** [comment]
Will keep open so we have an issue to update templates
