### ISSUE TITLE
Designer does not respect desired size of control being edited.

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/AvaloniaVS#25]
It always seems to display at a fixed size.

**Comment by ImaBrokeDude** [comment]
Are you using Desgner:Height and Designer:Width?

**Comment by ImaBrokeDude** [comment]
Oh this is because it will wrap a control in a window if the control is not actually a window. You would not be able to change the size of the control because it's set to fill the window. I think a simple binding would make this possible.

**Comment by grokys** [comment]
No I'm not using the Designer properties. I'm not sure what you mean - each control has a `DesiredSize` which you can use to auto-size the designer when the size isn't explicitly set using `Designer.Width` or `Designer.height`.

**Comment by ImaBrokeDude** [comment]
Ih is the control by itself?

**Comment by grokys** [comment]
I'm not sure what you mean. What I mean is that if you have a `Window` and you set `SizeToContext=WidthAndHeight` then the window in the designer should auto-size itself to its content the same as it does when when the application is run.

**Comment by Seeker1437** [comment]
Ofc but, this isn't set when the control is added as the `Windows`'s content.

**Comment by Seeker1437** [comment]
Basically it's 

```
control = getControl()
window = control as Window;
if (window == null)
      var window = new window
      window.Content = control

Designer.Show(window);
```
down to the purest sense inside the designer.

**Comment by grokys** [comment]
I'm not sure what you're trying to say, but try this in VS with WPF:

- Create a new `Window`
- Add a `TextBlock` with some text
- Set `Window.SizeToContent="WidthAndHeight"`
- Notice how the designer resizes to fit the window contents.

**Comment by grokys** [comment]
Looks like I was a bit wrong - if I enter `Window.SizeToContent="WidthAndHeight"` it does resize.

However if I don't set a size in e.g. `BindingTest\MainWindow.xaml` I get controls cut off:

![image](https://cloud.githubusercontent.com/assets/1775141/13556460/842e2cc6-e3da-11e5-965c-7b1b271b4200.png)

**Comment by Seeker1437** [comment]
A PR was submitted and merge that should correct this issue for isers of the lastest nightly build. Please test this and, if resolved, you may close this issue.
