### ISSUE TITLE
Error when switching from Split View to XAML View

### ISSUE THREAD

**Issue by anovik** [AvaloniaUI/AvaloniaVS#261]
I open the project, any of *.axaml file in designer (Windows 10, VS 2022 with all updates, Avalonia 0.10.16). No errors, designer works fine. 

I press XAML view to hide the designer. This all works but at the top left corner the following error appears:

![xaml_view_error](https://user-images.githubusercontent.com/8667411/179167738-518e4033-5fda-48b4-bfd2-53e4f1183425.png)

**Comment by maxkatz6** [comment]
Can you check output logs? There might be useful information.

![image](https://user-images.githubusercontent.com/3163374/179169903-2d5d505d-08c0-42f3-8e66-02dd4672122f.png)

**Comment by anovik** [comment]
There is not much info there. In Designer mode I had:

10:31:50.846 [Information]  Avalonia Package initialized
10:31:58.304 [Information] 0 Starting previewer process for '"MyProject.dll"'
10:31:58.319 [Information] 2228 Started previewer process for '"MyProject.dll"'. Waiting for connection to be initialized.
10:31:58.684 [Information] 2228 Connection initialized

After switching to XAML View:

10:33:48.548 [Information] 2228 Stopping previewer process
10:33:48.553 [Information]  Process exited
10:33:48.553 [Information]  Stopping previewer process
