### ISSUE TITLE
When I open axaml file,I got a error and the designer always show loading.....

### ISSUE THREAD

**Issue by UnivexDont** [AvaloniaUI/AvaloniaVS#268]
Describe the bug

To Reproduce

When I open axaml file,I got a error and the designer always show loading.....
[Error] 3816 <= "Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'RManServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'."
21:52:18.325 [Error] 3816 <= " at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)"
21:52:18.326 [Error] 3816 <= " at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)"
21:52:18.326 [Error] 3816 <= " at System.Reflection.Assembly.LoadFile(String path)"
21:52:18.327 [Error] 3816 <= " at Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint.Main(String[] cmdline) in //src/Avalonia.DesignerSupport/Remote/RemoteDesignerEntryPoint.cs:line 167"
21:52:18.328 [Error] 3816 <= " at Avalonia.Designer.HostApp.Program.Main(String[] args) in //src/tools/Avalonia.Designer.HostApp/Program.cs:line 47"
21:52:21.499 [Information] Process exited
21:52:21.500 [Verbose] Started PreviewerProcess.Stop()
21:52:21.500 [Information] Stopping previewer process
21:52:21.501 [Verbose] Finished PreviewerProcess.Stop()
21:52:21.499 [Error] Connection error
System.IO.IOException: 无法从传输连接中读取数据: 远程主机强迫关闭了一个现有的连接。。 ---> System.Net.Sockets.SocketException: 远程主机强迫关闭了一个现有的连接。
在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
在 System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
--- 内部异常堆栈跟踪的结尾 ---
在 System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
在 System.Threading.Tasks.TaskFactory1.FromAsyncTrimPromise1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
在 Avalonia.Remote.Protocol.BsonStreamTransportConnection.d__15.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
在 Avalonia.Remote.Protocol.BsonStreamTransportConnection.d__16.MoveNext()
Expected behavior

Screenshots
![image](https://user-images.githubusercontent.com/29479617/193623300-8aa6a68d-a267-4b24-91e9-68f8e7a3f0d2.png)

Desktop (please complete the following information):

Windows11 preview ARM M1
-2. VS 2022 preview M1 ARM
Additional context
Please give me some help, Thanks so much.....

**Comment by OVPNCoin** [comment]
Hi Avalonia team. 
Same issue.... =(
I create new project, do not add any code. Just add new Avalonia window and it is not working. 
"The designer is loading".

VS2022 community, Win10.

**Comment by maxkatz6** [comment]
> I create new project, do not add any code. Just add new Avalonia window and it is not working.

Project needs to be built. Also check logs in Avalonia Diagnostics.

**Comment by MikeCodesDotNET** [comment]
We should gracefully handle the app not having been built and perhaps display a warning in the previewer.

**Comment by MikeCodesDotNET** [comment]
Perhaps this would help? 

https://user-images.githubusercontent.com/552074/201112392-74a62f59-9873-4d06-9719-530c13605094.mp4
