### ISSUE TITLE
ARM64 VS2022 compatibility?

### ISSUE THREAD

**Issue by ggppjj** [AvaloniaUI/AvaloniaVS#270]
Hello! I have a Thinkpad X13s, an ARM64 Windows device. It's pretty good, and Microsoft has released an ARM native build of VS2022. They very recently started allowing extensions to target ARM64 VS2022, and as of yet the marketplace for ARM64 is very lacking in general. I have absolutely no idea what would be required for this, but would like to open this issue to explore the possibility of submitting the extension for the ARM64 marketplace also.

Thank you for your time.

**Comment by ggppjj** [comment]
According to Microsoft, as long as the project is set to build for Any CPU (as this appears to be setup for), all that should have to happen is adding arm64 as a target. I added it and ran a build against an unchanged main branch, that does appear to have built and installed correctly in VS2022 Insiders 15.x whatever the newest is, I was able to install it and verify that it at least looked fine from a surface-level.

**Comment by maxkatz6** [comment]
Merged, but not yet available in the extensions store https://github.com/AvaloniaUI/AvaloniaVS/pull/282
