### ISSUE TITLE
Toggle AXAML Screen and Designer Screen

### ISSUE THREAD

**Issue by DicksHalfwayInn** [AvaloniaUI/AvaloniaVS#273]
In Wpf there is a "Swap Screen" button to position either the XAML or the designer screens on the left or right (in vertical split screen mode) or top and bottom (in horizontal split screen mode)
![SwapScreenButton](https://user-images.githubusercontent.com/43318833/205503841-49f9288e-167d-4425-a0a8-79dc388df230.PNG)

**Comment by waliarubal** [comment]
When is this feature coming? I have an ultra wide monitor and this feature is super essential for smooth development.
