### ISSUE TITLE
Intellisense fails to load with can't find System.Text.Json

### ISSUE THREAD

**Issue by amwx** [AvaloniaUI/AvaloniaVS#298]
`master` will fail to initialize intellisense with Avalonia completions with an error about not being able to load `System.Text.Json`.

![image](https://user-images.githubusercontent.com/40413319/219512868-03c051fe-9f36-4899-a506-e02ba3a768f5.png)

This is because VS ships with its own reference to System.Text.Json, which in my install (17.4.4) is `6.0.2`, but the completion engine is using `7.0.1` so VS fails to find it. I changed the completion engine to match versions and it fixes it. However, I don't know how often VS updates that so older versions may be using an even older version of the dll. 

So either we need to
- revert this change and go back to newtonsoft 
- find a way to keep the dll version compatible or use an old enough version to avoid issues

[This stackoverflow post](https://stackoverflow.com/questions/74788219/visual-studio-extension-fails-when-parsing-json-due-to-not-finding-microsoft-bc) which is a similar issue also suggests a way to suppress loading the default VS version in the VISX, but I couldn't get it to work (but I also don't have enough knowledge on msbuild either). 

cc @maxkatz6

**Comment by maxkatz6** [comment]
We can take the oldest https://www.nuget.org/packages/System.Text.Json/4.6.0 version we can use. Whatever newer version VS ships, their one will be used.
