### ISSUE TITLE
Unable to preview xaml under ControlCatalog item in Avalonia Samples

### ISSUE THREAD

**Issue by bodong1987** [AvaloniaUI/AvaloniaVS#309]
There is basically no problem with the xaml in the ordinary avalonia project, but this project cannot be previewed, which is a bit strange.
this is the error log:

`20:58:37.785 [Information]  Starting previewer process for '"G:\Avalonia\samples\ControlCatalog.Browser\bin\Debug\net7.0\browser-wasm\ControlCatalog.Browser.dll"'
20:58:37.795 [Information] 35668 Started previewer process for '"G:\Avalonia\samples\ControlCatalog.Browser\bin\Debug\net7.0\browser-wasm\ControlCatalog.Browser.dll"'. Waiting for connection to be initialized.
20:58:37.835 [Error] 35668 <= "A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'G:\Avalonia\samples\ControlCatalog.Browser\bin\Debug\net7.0\browser-wasm\'."
20:58:37.836 [Information]  Process exited while waiting for connection to be initialized.
20:58:37.836 [Information]  Process exited
20:58:37.837 [Information]  Stopping previewer process
20:58:37.836 [Error]  <= "Failed to run as a self-contained app."
20:58:37.838 [Error]  <= "  - The application was run as a self-contained app because 'G:\Avalonia\samples\ControlCatalog.Browser\bin\Debug\net7.0\browser-wasm\ControlCatalog.Browser.runtimeconfig.json' did not specify a framework."
20:58:37.839 [Error]  <= "  - If this should be a framework-dependent app, specify the appropriate framework in 'G:\Avalonia\samples\ControlCatalog.Browser\bin\Debug\net7.0\browser-wasm\ControlCatalog.Browser.runtimeconfig.json'."
`

this is the runtime_config.json for ControlCatalog.Browser.dll
`{
  "runtimeOptions": {
    "tfm": "net7.0",
    "includedFrameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "7.0.3"
      }
    ],
    "wasmHostProperties": {
      "perHostConfig": [
        {
          "name": "browser",
          "html-path": "index.html",
          "Host": "browser"
        }
      ]
    },
    "configProperties": {
      "Microsoft.Extensions.DependencyInjection.VerifyOpenGenericServiceTrimmability": true,
      "System.ComponentModel.TypeConverter.EnableUnsafeBinaryFormatterInDesigntimeLicenseContextSerialization": false,
      "System.Resources.ResourceManager.AllowCustomResourceTypes": false,
      "System.Runtime.InteropServices.BuiltInComInterop.IsSupported": false,
      "System.Runtime.InteropServices.EnableConsumingManagedCodeFromNativeHosting": false,
      "System.Runtime.InteropServices.EnableCppCLIHostActivation": false,
      "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization": false,
      "System.StartupHookProvider.IsSupported": false,
      "System.Threading.Thread.EnableAutoreleasePool": false,
      "System.Text.Encoding.EnableUnsafeUTF7Encoding": false
    }
  }
}`

I tried to directly copy the hostpolicy.dll of .net 7, but another error was reported:
`21:05:14.891 [Information] 0 Starting previewer process for '"G:\Avalonia\samples\ControlCatalog.Browser\bin\Debug\net7.0\browser-wasm\ControlCatalog.Browser.dll"'
21:05:14.902 [Information] 45560 Started previewer process for '"G:\Avalonia\samples\ControlCatalog.Browser\bin\Debug\net7.0\browser-wasm\ControlCatalog.Browser.dll"'. Waiting for connection to be initialized.
21:05:14.948 [Error] 45560 <= "Could not resolve CoreCLR path. For more details, enable tracing by setting COREHOST_TRACE environment variable to 1"
21:05:14.950 [Information]  Process exited while waiting for connection to be initialized.
21:05:14.954 [Information]  Process exited
21:05:14.958 [Information]  Stopping previewer process
`

So, what causes this? Is there any way to solve this?
I use Visual Studio 2022.

**Comment by sczybt** [comment]
here:https://github.com/AvaloniaUI/Avalonia/tree/master/samples

**Comment by jamsoft** [comment]
Can you describe the fix in more detail please? I'm having the same issue and the link isn't particularly helpful.
