### ISSUE TITLE
Failed to register an invisible editor in PerspexEditorFactory

### ISSUE THREAD

**Issue by abdelkarim** [AvaloniaUI/AvaloniaVS#31]
got the following exception, after opening vs, a perspex xaml file were open in a previous session, but not selected. I got the exception after selecting it.

![image](https://cloud.githubusercontent.com/assets/1153480/13429580/350ad2f6-dfc1-11e5-9e6c-1242b17a09fa.png)

**Comment by Seeker1437** [comment]
Check out the third answer not sure if this might be helpful.

https://social.msdn.microsoft.com/Forums/sqlserver/en-US/eb6429f3-e5e4-4312-8058-9490f2c698ed/sdk-package-converting-ivsinvisibleeditor-into-something-less-invisible?forum=vsx
