### ISSUE TITLE
Cannot edit axaml in 0.10.18.1

### ISSUE THREAD

**Issue by bruxe0000** [AvaloniaUI/AvaloniaVS#313]
Hi, after upgrading to 0.10.18.1, I cannot edit the axaml file anymore. Is there any solution to downgrade the extension's version?

**Comment by Takoooooo** [comment]
May you please attach some videos,any discription of what happens to let us debug? Previous VSIX version is
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/AvaloniaTeam/vsextensions/AvaloniaVS/0.10.18/vspackage

**Comment by robsoncorreia** [comment]
Hi, I cannot edit the axaml file after upgrading to 0.10.18.1.
Can you tell me why?

**Comment by nightfog-git** [comment]
Hi, I've got the same problem, here is some information, hope this helps.

After an update from 0.10.18 to 0.10.18.1 there are no Avalonia templates anymore in new projects. Existing projects are loading and building successfully, xaml designer is opening ok. But any attempt to edit the xaml code is ignored, I can navigate the code with keyboard arrows, but new symbols not printed. 
The backspace hit leads to an error
![error](https://user-images.githubusercontent.com/91830763/222440273-b9cf57ef-2812-4960-aa5a-8904adfe5eaf.png)

The system is Win10, VS 2019 16.11.24 (latest update), projects targeting .NET5.0 and core 3.1.
Reverting back to 0.10.18 restores the functionality.

**Comment by maxkatz6** [comment]
> there are no Avalonia templates anymore in new projects

Use .NET CLI templates or upgrade to VS 2022. 

Code editing issue should be fixed though. 
Probably similar to the https://github.com/AvaloniaUI/AvaloniaVS/issues/298

**Comment by bruxe0000** [comment]
On VS2019, temporarily, I fixed this by reversing version 0.10.18.1 to 0.10.18. The link is below:
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/AvaloniaTeam/vsextensions/AvaloniaforVisualStudio/0.10.18/vspackage

**Comment by Takoooooo** [comment]
Release 0.10.18.2 is out,feel free to test
