### ISSUE TITLE
[Feature Request]: generate code behind method if an Event is defined in the XAML

### ISSUE THREAD

**Issue by timunie** [AvaloniaUI/AvaloniaVS#317]
In WPF, if you type this XAML

```xml
<Button Click="Button_Click" />
```

a new method will be added in code behind (if not present) that matches to the reqiuered argument args

```cs
private void Button_Click (object sender, RoutedEventArgs e) 
{
   ...
}
```

is it possible to add this to the Avalonia extension as well? 

Note: Rider supports this, but not everyone can switch to Rider. 

Related: https://github.com/AvaloniaUI/Avalonia/discussions/10621 

/cc @giziben

**Comment by kadir-ince** [comment]
Is there any plan for this request? We are too dependent on Visual Studio, can't switch to Rider and ReSharper slows down Visual Studio.

**Comment by timunie** [comment]
The issue is labeled with `help-wanted`, so I guess if none of the community memebers step in and file a PR this could take some time until it's finally implemented. It's planned for sure. Maybe @Takoooooo , do you have an estimation if that is possible?

**Comment by Takoooooo** [comment]
I am planning to try to implement that in a few days. But i can't guarantee that i will have success with that ;)

**Comment by timunie** [comment]
Hoaw this looks hard... Hope you can find a solution as it looks like your are half way there.
