### ISSUE TITLE
error in Visual Studio 2022

### ISSUE THREAD

**Issue by hanhaowen** [AvaloniaUI/AvaloniaVS#326]
I have installed the extension through visual studio extension management tools in Visual Studio 2022.
![image](https://user-images.githubusercontent.com/70024226/230700481-a13e4411-cd64-420c-8fd8-d1dda479a61c.png)
But when I create a Avalonia MVVM project for the first time, I get the following errors:
![image](https://user-images.githubusercontent.com/70024226/230700545-66abb629-5b5b-480a-947e-001a31d2e9b1.png)
It means that the Visual Studio can not find these packages such as Avalonia.Desktop and so on. What'more, the left colomn also shows that Visual Studio can not find the Avalonia dependency packages.

**Comment by maxkatz6** [comment]
It's not an Avalonia problem.
Hard to tell from the error as it's not in English, but I assume it can't restore nuget packages.
Double check that you have nuget packages source set up in the Visual Studio (should be there by default).
And maybe you need a VPN to access this package source.
See https://learn.microsoft.com/en-us/nuget/consume-packages/package-restore-troubleshooting
