### ISSUE TITLE
Designer Not Loading - Visual Studio 2022

### ISSUE THREAD

**Issue by ward-horsfall** [AvaloniaUI/AvaloniaVS#332]
Hi,

I am using Visual Studio Community 17.6.2.

From this step I installed the templates URL: https://docs.avaloniaui.net/docs/getting-started

dotnet new install Avalonia.Templates

I also installed the following Extensions:

Avalonia Toolkit - Version 0.1.2
Avalonia for Visual Studio 2022 - Version 0.10.18.2

I then try to create a "Avalonia .NET Core App (AvaloniaUI)" App.

Avalonia Version 0.10.21 with .NET 7 and two the two issues are:

The is a red icon in the top left corner.
The designer window is stuck on "The designer is loading..."

Thanks

Ward.

![Screen1](https://github.com/AvaloniaUI/AvaloniaVS/assets/12206371/45ee2732-62a4-4515-9864-113136a5c242)
![Screen3](https://github.com/AvaloniaUI/AvaloniaVS/assets/12206371/26e6f371-7507-4e02-813a-3cb0445f3b7a)

**Comment by ward-horsfall** [comment]
Hi maxkatz6,

Um no it was not. Ok I tried that problem went away. However there is no toolbox for the controls to drag and drop?

Is there something else I am missing?

Thanks

Ward

**Comment by maxkatz6** [comment]
No. It's a previewer for your XAML code. Not a drag'n'drop designer, so this is an expected behavior.

**Comment by ward-horsfall** [comment]
Hi maxkatz6,

Thanks for your excellent help. Ok I was hoping to create a XPF application and test.

Is this too soon yet? (Looks like there are a few different project types I am now assuming - and I was not creating and XPF type after all).

If not are there specific steps you can point me to do that?

Thanks

Ward.
