### ISSUE TITLE
Previewer no longer treats .xaml files as design files

### ISSUE THREAD

**Issue by emmauss** [AvaloniaUI/AvaloniaVS#345]
### Describe the bug

On 0.10.18.3, .xaml files are no longer recognized as designer files, even if specified as so in the project file.

### To Reproduce

Add a new usercontrol and rename it to a .xaml file

### AvaloniaVS plugin version

0.10.18.3

### Avalonia version

11.0.0-rc-1.1

### Visual Studio version

17.5.1

### Relevant log output

```shell
17:40:45.342 [Information]  Avalonia Package initialized
```

**Comment by emmauss** [comment]
All designer file in the Avalonia UI project use the xaml extension. If .xaml is no longer supported, then those files needs to be renamed.

**Comment by kekekeks** [comment]
We have no control over the `.xaml` file extension. VS have broken our support for it so many times, so there is no point in bothering to support it again. `.axaml` file extension was introduced specifically because of VS breaking our support for `.xaml` every couple of months.

**Comment by Takoooooo** [comment]
fixed by https://github.com/AvaloniaUI/AvaloniaVS/pull/346
