### ISSUE TITLE
System.Xaml.XamlException

### ISSUE THREAD

**Issue by chenzanyu** [AvaloniaUI/AvaloniaVS#348]
### Describe the bug

Install Avalonia for Visual Studio 2022 template, it automatically installs the Avalonia Template Studio template, create a desktop application, modify the content of MainView.axaml, the designer is throwing an exception, and it reports: "[Error] 34228 UpdateXamlResult error System.Xaml.XamlException: “Name cannot begin with the ‘<’ character, hexadecimal value 0x3C. Line 16, position 1.”

### To Reproduce

template program

### AvaloniaVS plugin version

0.10.18.4

### Avalonia version

11.0.0-rc1.1

### Visual Studio version

VisualdStudio2022 Version: 17.63

### Relevant log output

```shell
01:02:43.434 [Information] 34228 Connection initialized
01:02:53.202 [Error] 34228 UpdateXamlResult error
System.Xaml.XamlException: “Name cannot begin with the '
' character, hexadecimal value 0x0D. Line 15, position 4.”，行号为“15”，行位置为“4”。
01:02:53.827 [Error] 34228 UpdateXamlResult error
System.Xaml.XamlException: “Name cannot begin with the '<' character, hexadecimal value 0x3C. Line 16, position 1.”，行号为“16”，行位置为“1”。
01:02:54.476 [Error] 34228 UpdateXamlResult error
System.Xaml.XamlException: “Name cannot begin with the '<' character, hexadecimal value 0x3C. Line 16, position 1.”，行号为“16”，行位置为“1”。
```

**Comment by maxkatz6** [comment]
Please add more information. How exactly edited MainView.axaml looks like?

**Comment by chenzanyu** [comment]
this is MainView.axaml Code 
`<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:vm="clr-namespace:AvaloniaApplication9.ViewModels"
             mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
             x:Class="AvaloniaApplication9.Views.MainView"
             x:DataType="vm:MainViewModel">
  <Design.DataContext>
    
    <vm:MainViewModel />
  </Design.DataContext>

	<Grid>
	</Grid>
</UserControl>`

**Comment by chenzanyu** [comment]
Simply replacing the automatically generated TextBox with Grid or any other element causes the designer to malfunction until F5 is clicked to run the project again.

**Comment by chenzanyu** [comment]
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:vm="clr-namespace:AvaloniaApplication9.ViewModels"
             mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
             x:Class="AvaloniaApplication9.Views.MainView"
             x:DataType="vm:MainViewModel">
  <Design.DataContext>
    
    <vm:MainViewModel />
  </Design.DataContext>

	<Grid>
	</Grid>
</UserControl>

**Comment by chenzanyu** [comment]
`<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:vm="clr-namespace:AvaloniaApplication9.ViewModels"
             mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
             x:Class="AvaloniaApplication9.Views.MainView"
             x:DataType="vm:MainViewModel">
  <Design.DataContext>
    <vm:MainViewModel />
  </Design.DataContext>

	<Grid>
	</Grid>
</UserControl>`

**Comment by chenzanyu** [comment]
The designer works fine after updating to v11.0.0
