### ISSUE TITLE
Zoom does not work in XAML previewer

### ISSUE THREAD

**Issue by AtomCrafty** [AvaloniaUI/AvaloniaVS#350]
### Describe the bug

The previewed contents do not change in size when I zoom in design mode. If I zoom out, the contents will be clipped and if I zoom in, they will fill only a portion of the intended bounds indicated by the shadow outline.

Demo video: https://youtu.be/RPazjrdEmtk

### To Reproduce

- Create a new Avalonia project
- Open MainView.axaml
- Switch to split view or design view
- Ctrl + scroll or use the zoom dropdown

### AvaloniaVS plugin version

0.10.18.4

### Avalonia version

11.0.0-rc1.1

### Visual Studio version

17.6.4

### Relevant log output

```shell
21:00:14.223 [Information] 0 Starting previewer process for '"D:\Code\Tests\AvaloniaPreviewerTest\AvaloniaPreviewerTest.Desktop\bin\Debug\net7.0\AvaloniaPreviewerTest.Desktop.dll"'
21:00:14.226 [Information] 28620 Started previewer process for '"D:\Code\Tests\AvaloniaPreviewerTest\AvaloniaPreviewerTest.Desktop\bin\Debug\net7.0\AvaloniaPreviewerTest.Desktop.dll"'. Waiting for connection to be initialized.
21:00:14.648 [Information] 28620 Connection initialized
```

### Additional context

Unsuccessful attempts to resolve the issue:
- Restarted Visual Studio
- Reinstalled the extension
- Updated Visual Studio to the latest version
- Rebooted Windows

**Comment by MrJul** [comment]
Please try 11.0.0 RC2.2, there were a lot of fixes for the previewer between RC1 and 2.

**Comment by AtomCrafty** [comment]
Thanks, that seems to have fixed the issue.
