### ISSUE TITLE
[Feature] TextTrimming Autocomplete

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/AvaloniaVS#354]
### Is your feature request related to a problem? Please describe.

TextTrimming Autocomplete

### Describe the solution you'd like

TextTrimming Autocomplete

**Comment by maxkatz6** [comment]
No need to add a special support for that yet.
I am planning to implement EnumPropertyAttribute or something like this, so we can keep the compiler in sync with custom properties that behave like enum, but are not. Same for TransparencyLevels and ThemeVariants.
So once we have compiler (VS and Rider) support for this attribute, all of these and newer properties would just work.
