### ISSUE TITLE
XAML preview fails when TargetPlatform is set to net7.0-windows10.0.22621.0

### ISSUE THREAD

**Issue by HEIC-to-JPEG-Dev** [AvaloniaUI/AvaloniaVS#369]
**Describe the bug**
When I change from Net7.0 to <TargetFramework>net7.0-windows10.0.22621.0</TargetFramework> the previewer fails.

![image](https://github.com/AvaloniaUI/Avalonia/assets/32410442/971a5361-ffab-4e85-b941-2c6030c46bae)

**To Reproduce**
change the target framework

**Comment by Takoooooo** [comment]
I can't repro,may you record a video or GIF of how to repro it?

**Comment by HEIC-to-JPEG-Dev** [comment]
I changed it back to net7.0 - but now no XAML preview is displayed. I'm not sure how to get the previewer to display ?

**Comment by HEIC-to-JPEG-Dev** [comment]
Done that several times, also "clean solution" and "delete all the obj/bin" - still no joy, it doesn;t offer any preview (not even the red icon above the xaml"

**Comment by timunie** [comment]
@HEIC-to-JPEG-Dev any chance you can file a minimal sample for @Takoooooo to test on his own? Maybe you have something "special" that we don't see rn.

**Comment by Takoooooo** [comment]
This issue should be fixed by https://github.com/AvaloniaUI/AvaloniaVS/pull/368
