### ISSUE TITLE
AXAML Preview Not Working After Switching from .NET Core to .NET Framework

### ISSUE THREAD

**Issue by kadir-ince** [AvaloniaUI/AvaloniaVS#370]
### Description

I've encountered an issue where the AXAML preview does not function after changing the project's target framework from .NET Core to .NET Framework 4.8.
![260431058-971a5361-ffab-4e85-b941-2c6030c46bae](https://github.com/AvaloniaUI/AvaloniaVS/assets/52853427/96d3fbd0-f8b5-46e8-904c-b36bfa3e679a)

### Expected Behavior

Switching the target framework should not affect the functionality of the AXAML preview. It should work consistently regardless of whether the project targets .NET Core or .NET Framework 4.8.

### Actual Behavior

After transitioning to .NET Framework 4.8, the AXAML preview ceases to work.
 

### To Reproduce

1. Create a new Avalonia project targeting .NET Core.
2. Ensure that the AXAML preview works correctly.
3. Change the target framework of the project to .NET Framework 4.8 in csproj.
4. Notice that the AXAML preview no longer functions.

### AvaloniaVS plugin version

11.0

### Avalonia version

11.0.0

### Visual Studio version

17.7.1

**Comment by Takoooooo** [comment]
Released AvaloniaVS with a fix for that issue,please try it

**Comment by kadir-ince** [comment]
**When I tried building and testing the commit you provided, it worked; now, when I try the release version, that also works.**

![image](https://github.com/AvaloniaUI/AvaloniaVS/assets/52853427/eade996d-74ae-49d3-820e-6eeb5f99565e)
