### ISSUE TITLE
"Catastrophic failure" error message while opening .axaml files.

### ISSUE THREAD

**Issue by abhaynath** [AvaloniaUI/AvaloniaVS#399]
### Describe the bug

Since new update, designer and intellisence stopped working. I just get "Catastrophic failure" error message.

I tried to install older version, but I didn't find older version VSIX file.

### To Reproduce

- Install updated extension
- Open any .axaml file

### AvaloniaVS plugin version

11.3

### Avalonia version

11

### Visual Studio version

17.6.4

### Relevant log output

```shell
didn' attached any logs
```

**Comment by Takoooooo** [comment]
Can you please try installing 11.2 version
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/AvaloniaTeam/vsextensions/AvaloniaVS/11.2/vspackage
or 
11.1
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/AvaloniaTeam/vsextensions/AvaloniaVS/11.1/vspackage
And check if that works for you?

**Comment by Lazuden** [comment]
@Takoooooo thanks
Same problem. It works after installing 11.1 (didnt check 11.2).

**Comment by Takoooooo** [comment]
What happens if you close and re-open the axaml  file? Still failure?

**Comment by Takoooooo** [comment]
May you guys test this extension? And test the event completions also if possible
[AvaloniaVS.VS2022 (2).zip](https://github.com/AvaloniaUI/AvaloniaVS/files/12858992/AvaloniaVS.VS2022.2.zip)

**Comment by abhaynath** [comment]
> Can you please try installing 11.2 version https://marketplace.visualstudio.com/_apis/public/gallery/publishers/AvaloniaTeam/vsextensions/AvaloniaVS/11.2/vspackage or 11.1 https://marketplace.visualstudio.com/_apis/public/gallery/publishers/AvaloniaTeam/vsextensions/AvaloniaVS/11.1/vspackage And check if that works for you?

Tried with 11.2

https://marketplace.visualstudio.com/_apis/public/gallery/publishers/AvaloniaTeam/vsextensions/AvaloniaVS/11.2/vspackage

Its working properly on my system.

**Comment by Lazuden** [comment]
> May you guys test this extension? And test the event completions also if possible. And i will get a fix for you today [AvaloniaVS.VS2022 (2).zip](https://github.com/AvaloniaUI/AvaloniaVS/files/12858992/AvaloniaVS.VS2022.2.zip)

now its ok, displays as 11.3 and works

**Comment by abhaynath** [comment]
> May you guys test this extension? And test the event completions also if possible. And i will get a fix for you today [AvaloniaVS.VS2022 (2).zip](https://github.com/AvaloniaUI/AvaloniaVS/files/12858992/AvaloniaVS.VS2022.2.zip)

Working fine ! Thanks !!

**Comment by Takoooooo** [comment]
Thanks guys,will make a release ASAP
