### ISSUE TITLE
[DevTools] Copy Selector replace Clr Namespace with xmlns

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/AvaloniaVS#448]
## Is your feature request related to a problem? Please describe.

Speed up writing a Style Selector. 
When Copy Selector using [DevTools] treeview context menu, it put text like this in clipboard:

`FluentAvalonia.UI.Controls.NavigationView#NavView.Store /template/ Avalonia.Controls.ScrollViewer#FooterItemsScrollViewer`

## Describe the solution you'd like
When Copy Selector using [DevTools] treeview context menu it put text like this in clipboard:

`ui|NavigationView#NavView.Store /template/ ScrollViewer#FooterItemsScrollViewer`

**Comment by timunie** [comment]
@workgroupengineering transferred as requested
