### ISSUE TITLE
Broken installation on linux

### ISSUE THREAD

**Issue by Mek101** [AvaloniaUI/AvaloniaVS#457]
### Describe the bug

Installing the extensions fails with an error as the scripts in `/home/mek101/.vscode-oss/extensions/ms-dotnettools.vscode-dotnet-runtime-2.0.2/dist/install scripts/` don't have executable permission.

```
$ ls -l
totale 152
-rw-r--r-- 1 mek101 mek101   875  4 mar 16.13 determine-linux-distro.sh
-rw-r--r-- 1 mek101 mek101 70702  4 mar 16.13 dotnet-install.ps1
-rw-r--r-- 1 mek101 mek101 62330  4 mar 16.13 dotnet-install.sh
-rw-r--r-- 1 mek101 mek101  7541  4 mar 16.13 install-linux-prereqs.sh
-r--r--r-- 1 mek101 mek101  1718  4 mar 16.13 interprocess-communicator.sh
```

### To Reproduce

Try to install the extension on a linux OS. 

### AvaloniaVS plugin version

v0.0.31

### Visual Studio version

None. Visual Studio Code

### Relevant log output

```shell
Lost after trying to uninstalling and reinstalling the extension
```

**Comment by maxkatz6** [comment]
It's a Visual Studio extension, you can't install it on Linux.

If you need VSCode, see https://github.com/AvaloniaUI/AvaloniaVSCode.
