### ISSUE TITLE
Remove dependency from Avalonia TemplateStudio

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/AvaloniaVS#477]
### Is your feature request related to a problem? Please describe.

[Avalonia TemplateStudio](https://github.com/AvaloniaUI/TemplateStudio) currently does not work with the latest VS versions and it is currently not maintained.

### Describe the solution you'd like

Temporarily remove the dependency from Avalonia TemplateStudio

**Comment by maxkatz6** [comment]
TemplateStudio is planned to be updated once 11.1 released
