### ISSUE TITLE
Preview window is blinking permanently

### ISSUE THREAD

**Issue by Sergey-Terekhin** [AvaloniaUI/AvaloniaVS#48]
I've installed latest version of extension in VS 2017 community and got bug in the preview window:

![designer_fail](https://cloud.githubusercontent.com/assets/5369802/26061013/696412dc-398f-11e7-8b36-94880d9e1cbf.gif)

**Comment by grokys** [comment]
This should be fixed by 0.8.0. Please comment if it's not!
