### ISSUE TITLE
File Templates not available for Core Projects

### ISSUE THREAD

**Issue by peterjeschke** [AvaloniaUI/AvaloniaVS#49]
I assume the File Templates (User Control, Window) should be available for core projects, too. Currently, it's not possible to select them in the new dialog. I think it should be fixed by removing [this](https://github.com/AvaloniaUI/AvaloniaVS/blob/467b328a40e43e2442f39d309b26a10246047686/src/Templates/AvaloniaUserControlTemplate/AvaloniaUserControlTemplate.vstemplate#L9) line, but I cannot build the project, so I can't create a PR myself.

**Comment by SinZ163** [comment]
+1 this
