### ISSUE TITLE
VS for Mac port

### ISSUE THREAD

**Issue by jhonatn** [AvaloniaUI/AvaloniaVS#50]
Is there a possibility for this to be ported to Visual Studio for Mac? (formerly Xamarin Studio. It also uses the XS extension framework, not the VS one)

**Comment by gravldo** [comment]
First - I applaud the effort to get a truly cross-platform tool to work between Windows and the Mac, as Xamarin says it does, but the actual code and coding doesn't as Windows is XAML and Mac is XIB...and I don't really care that there was an Xcode dependency that exists or not, as Mono was targeted to be platform independent.  That said, now that VS 2017 GA includes Mac, please either port this or update the description to VS 2017 Windows only so people like me don't waste time downloading it and trying to install it on the mac.

**Comment by yevgeny-sotnikov** [comment]
Same from my side. When will be provided an ability to develop Avalonia from VS4mac?

**Comment by prashantvc** [comment]
Microsoft announced VS for Mac retirement. So closing this issue
https://devblogs.microsoft.com/visualstudio/visual-studio-for-mac-retirement-announcement/
