### ISSUE TITLE
Avalonia Designer is forced upon the user if it is not disabled

### ISSUE THREAD

**Issue by RexTremendae** [AvaloniaUI/AvaloniaVS#61]
**Steps to reproduce:**
* With the Designer still enabled, chose "Source View" as default view in options
* Open two XAML files
* Switch between the two files a couple of times

**Expected result:**
The source view should still be the default view until the user selects something else.

**Actual result:**
The designer view creeps up on, and forces itself upon the innocent and totally unsuspecting user.

**Workaround:**
Close the XAML file and reopen it again. Very annoying!

**Comment by donandren** [comment]
should be fixed by #76  when merged

**Comment by grokys** [comment]
#115 added an options dialog to let you choose the behavior.
