### ISSUE TITLE
Errors on fresh install of version AvaloniaVS 0.6.0.1

### ISSUE THREAD

**Issue by uxmal** [AvaloniaUI/AvaloniaVS#64]
I'm anxious to try out Avalonia as the new graphical front end for the [Reko decompiler](https://github.com/uxmal/reko). I used Visual Studio 2017's "Extensions and Updates" dialog to download AvaloniaVS. Version 0.6.01 installed. I added a new "Avalonia Application" in the `File` > `New` > `Project` dialog. The following is the result:
![image](https://user-images.githubusercontent.com/10154465/37300362-125d45a6-2626-11e8-8b44-e568da614d6d.png)
In the VStudio `Error List` I see:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0115	'App.Initialize()': no suitable method found to override	Avalonia(netcoreapp2.0)	C:\dev\uxmal\reko\master\src\Drivers\Avalonia\App.xaml.cs	8	Active
Error	NU1108	Cycle detected. 
  Avalonia -> Avalonia (>= 0.6.1).	Avalonia	C:\dev\uxmal\reko\master\src\Drivers\Avalonia\Avalonia.csproj	1	
Error	NU1108	Cycle detected. 
  Avalonia -> Avalonia (>= 0.6.1).	Avalonia	C:\dev\uxmal\reko\master\src\Drivers\Avalonia\Avalonia.csproj	1	
Error	CS0103	The name 'AppBuilder' does not exist in the current context	Avalonia(net461), Avalonia(netcoreapp2.0)	C:\dev\uxmal\reko\master\src\Drivers\Avalonia\Program.cs	15	Active
Error	CS0246	The type or namespace name 'AppBuilder' could not be found (are you missing a using directive or an assembly reference?)	Avalonia(net461), Avalonia(netcoreapp2.0)	C:\dev\uxmal\reko\master\src\Drivers\Avalonia\Program.cs	14	Active
Error	CS0246	The type or namespace name 'Application' could not be found (are you missing a using directive or an assembly reference?)	Avalonia(netcoreapp2.0)	C:\dev\uxmal\reko\master\src\Drivers\Avalonia\App.xaml.cs	6	Active
Error	CS0234	The type or namespace name 'Controls' does not exist in the namespace 'Avalonia' (are you missing an assembly reference?)	Avalonia(netcoreapp2.0)	C:\dev\uxmal\reko\master\src\Drivers\Avalonia\MainWindow.xaml.cs	2	Active
Error	CS0234	The type or namespace name 'Logging' does not exist in the namespace 'Avalonia' (are you missing an assembly reference?)	Avalonia(net461), Avalonia(netcoreapp2.0)	C:\dev\uxmal\reko\master\src\Drivers\Avalonia\Program.cs	3	Active
Error	CS0234	The type or namespace name 'Markup' does not exist in the namespace 'Avalonia' (are you missing an assembly reference?)	Avalonia(netcoreapp2.0)	C:\dev\uxmal\reko\master\src\Drivers\Avalonia\App.xaml.cs	2	Active
Error	CS0234	The type or namespace name 'Markup' does not exist in the namespace 'Avalonia' (are you missing an assembly reference?)	Avalonia(netcoreapp2.0)	C:\dev\uxmal\reko\master\src\Drivers\Avalonia\MainWindow.xaml.cs	3	Active
Error	CS0246	The type or namespace name 'Window' could not be found (are you missing a using directive or an assembly reference?)	Avalonia(netcoreapp2.0)	C:\dev\uxmal\reko\master\src\Drivers\Avalonia\MainWindow.xaml.cs	7	Active
```
My expectation was that this would work right off the bat. What am I doing wrong?

**Comment by grokys** [comment]
Hi, yes you're right that this should work off the bat. This is looking to me like a NuGet error, judging from `NU1108	Cycle detected`. Could you try doing a `nuget restore` or `dotnet restore` from the command line?

**Comment by uxmal** [comment]
Doing a `nuget restore`:
```
The folder 'c:\dev\uxmal\reko\master\src\Drivers\Avalonia' does not contain an msbuild solution or packages.config file to restore.
```
Doing a `dotnet restore`:
```
  Restoring packages for c:\dev\uxmal\reko\master\src\Drivers\Avalonia\Avalonia.csproj...
c:\dev\uxmal\reko\master\src\Drivers\Avalonia\Avalonia.csproj : error NU1108: Cycle detected.
c:\dev\uxmal\reko\master\src\Drivers\Avalonia\Avalonia.csproj : error NU1108:   Avalonia -> Avalonia (>= 0.6.1).
  Generating MSBuild file c:\dev\uxmal\reko\master\src\Drivers\Avalonia\obj\Avalonia.csproj.nuget.g.props.
  Restore failed in 337.01 ms for c:\dev\uxmal\reko\master\src\Drivers\Avalonia\Avalonia.csproj.
```
Contents of the freshly created directory:
```
 Directory of c:\dev\uxmal\reko\master\src\Drivers\Avalonia

03/12/2018  08:19 PM    <DIR>          .
03/12/2018  08:19 PM    <DIR>          ..
03/12/2018  08:19 PM               425 App.xaml
03/12/2018  08:19 PM               236 App.xaml.cs
03/12/2018  08:19 PM               580 Avalonia.csproj
03/12/2018  06:37 PM    <DIR>          bin
03/12/2018  08:19 PM               168 MainWindow.xaml
03/12/2018  08:19 PM               409 MainWindow.xaml.cs
03/12/2018  08:19 PM               195 nuget.config
03/12/2018  08:20 PM    <DIR>          obj
03/12/2018  08:19 PM               414 Program.cs
               7 File(s)          2,427 bytes
               4 Dir(s)  43,002,241,024 bytes free

**Comment by grokys** [comment]
Ok, it looks like something in the .NET SDK broke us :(

I will try to work out what the problem is, in the meantime if you edit your `.csproj` and remove `net461` from the `TargetFrameworks` that should fix it.

**Comment by uxmal** [comment]
Do you need a copy of my `.csproj` or any other files? I can zip up the contents if you like.

**Comment by uxmal** [comment]
Alas, removing `net461` from the `.csproj` file appears to make no difference.

**Comment by uxmal** [comment]
Interestingly, if I create a clean new .NET Framework Console Program and then add the Avalonia 0.6.1 package with the NuGet manager, I don't see any cycles. Could it have something to do with the new `.csproj` format used by .NET SDK?

**Comment by grokys** [comment]
Could you try removing the `nuget.config` file? I suspect it may be this bug: https://developercommunity.visualstudio.com/content/problem/195751/nuget-broken-in-vs-2017-156-preview-4-error-0x8000.html?childToView=213301#comment-213301.

Some users have reported that removing the `nuget.config` fixes it, and indeed it seems to allow me to build using `net461` on my machine.

**Comment by uxmal** [comment]
Removing the `nuget.config` doesn't change the problem. I still see:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1108	Cycle detected. 
  Avalonia -> Avalonia (>= 0.6.1).	Avalonia	C:\dev\uxmal\reko\master\src\Drivers\Avalonia\Avalonia.csproj	1	
```

**Comment by uxmal** [comment]
Well, egg on my face. It seems calling my project `Avalonia.csproj` confused NuGet. Renaming the project to `AvaloniaShell.csproj` seems to work. I figured this out after reading https://github.com/riganti/dotvvm/issues/525

In any case: thanks for your assistance! Looking forward to evaluating Avalonia.

**Comment by nicolasr75** [comment]
Egg on my face too, I fell into the same trap. Thanks for posting the solution!

**Comment by nathan130200** [comment]
Not working here `Error occurred while restoring NuGet packages: Failed to retrieve information about 'Avalonia' from remote source 'http://nuget.timpotze.nl/api/v2/FindPackagesById()?id='Avalonia'&semVerLevel=2.0.0'.`

**Comment by jetspiking** [comment]
I had the same issue just now on MacOS, for me the problem was that XCode was not properly installed. Performing "xcode-select --install" solved the issue.
