### ISSUE TITLE
NuGet.config at csproj level doesn't work

### ISSUE THREAD

**Issue by MihaMarkic** [AvaloniaUI/AvaloniaVS#65]
I'm seeing that NuGet.config created by this extension doesn't work if placed next to .csproj file, but it works when placed next to .sln.
Anybody seeing the same? 
VS 2017 15.8.2

**Comment by grokys** [comment]
Yes, this is a limitation of VS templates. Basically `nuget.config` only works when at the `.sln` level, but VS templates don't allow you to place stuff at the `.sln` level. I've added a comment to the `nuget.config ` file saying you need to move it manually to access the CI feed:

https://github.com/AvaloniaUI/AvaloniaVS/blob/master/templates/AvaloniaApplicationTemplate/nuget.config#L4
