### ISSUE TITLE
Resource not found after update to 0.8.0

### ISSUE THREAD

**Issue by ReIaxo** [AvaloniaUI/AvaloniaVS#82]
With Extension v0.7.0 all worked fine, after updating to v0.8.0, the previewer has the "reosurce not found" error message `System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\UserName\Path\to\Project\ProjectName\Resources\Images\outline_home_white_36dp.png'.` for my image resources. All the image deklarations looked like this where the "Resources" directory is toplevel in the project. BUT, Run works:
```xaml
<imaging:Bitmap x:Key="HomeIcon">
   <x:Arguments>
      <x:String>Resources/Images/outline_home_white_36dp.png</x:String>
   </x:Arguments>
</imaging:Bitmap>
```
Changing the lines above to the following makes the previewer work, but the project can't find the resource on runtime now:
```xaml
<imaging:Bitmap x:Key="HomeIcon">
   <x:Arguments>
      <x:String>ProjectName/Resources/Images/outline_home_white_36dp.png</x:String>
   </x:Arguments>
</imaging:Bitmap>
```

I think the relies to where the instance of the application runs for the previewer and the double project directory. `Path\ProjectName\ProjectName\bin\...`

**Comment by Gillibald** [comment]
I think you are using the file path overload here. That has nothing to do with resources because it tries to find the image in the file system. Unless the image isn't copied to the output folder that will fail.

**Comment by kekekeks** [comment]
I'm not sure if the current directory is a reliable way for previewer to locate resources.

**Comment by Gillibald** [comment]
We could introduce `IAssetLoader.ResolveFilePath(string relativePath)` to solve that. The naming isn't final.

**Comment by kekekeks** [comment]
We probably need another URI scheme for relative OS paths.
