### ISSUE TITLE
Intellisense Bug - double shown

### ISSUE THREAD

**Issue by furesoft** [AvaloniaUI/AvaloniaVS#85]
![image](https://user-images.githubusercontent.com/4117602/55631690-ea6b2480-57b8-11e9-9034-383f0d3a96ec.png)

**Comment by grokys** [comment]
@furesoft moved this to the AvaloniaVS repository so it can be tracked more easily.

**Comment by 0xaryan** [comment]
Happens to me on VS2019, Avalonia Extension v0.8.0.1
![image](https://user-images.githubusercontent.com/9091958/56206342-61c67100-6061-11e9-93c7-fefd614d11ac.png)

I realized when the IntelliSense Popup is not yet open (suggestion not started), when I type a character in  `WPFTextViewHost` it fires `AugmentCompletionSession` in `XamlCompletionSource` 2 times:

![image](https://user-images.githubusercontent.com/9091958/56209075-e4522f00-6067-11e9-8491-2f2266d9c360.png)

Is it normal?
