### ISSUE TITLE
Visual Studio XAML Window Layout Options

### ISSUE THREAD

**Issue by KinsonDigital** [AvaloniaUI/AvaloniaVS#89]
This is not a bug but more of a feature request.  

Could you please add the ability to be able to move the rendered window and the XAMAL code editor panes to be vertical side by side and horizontal above and below?

![image](https://user-images.githubusercontent.com/4921022/56378782-0c629f00-61dc-11e9-90ea-24dd8d206ae5.png)

**Comment by grokys** [comment]
Transferred this to the AvaloniaVS repository.

Yes! This is definitely planned!

**Comment by KinsonDigital** [comment]
Very cool! I think it would be great to be able to zoom in and out on the
rendered UI using the wheel of the mouse as well just like in a standard
WPF application.  😊
