### ISSUE TITLE
A more designer friendly "Markup Error" message for Previewer

### ISSUE THREAD

**Issue by 0xaryan** [AvaloniaUI/AvaloniaVS#93]
Currently Avalonia Previewer tries to immediately show an error message  while user is typing code ([it fails](https://github.com/AvaloniaUI/AvaloniaVS/issues/92) in that tho).
I think it's better to let user write the code, then decide to show any errors.

**WPF Designer approach:**
![vs-designer](https://user-images.githubusercontent.com/9091958/56461178-b3edf600-63c3-11e9-952e-013fa6f315e3.gif)

**Avalonia Previewer approach:**
![avalonia-previewer](https://user-images.githubusercontent.com/9091958/56461199-f9aabe80-63c3-11e9-9980-7c48ff714de7.gif)

Or if you think it should report the error immediately, I think XAML Studio's approach can be used too, it shows up an error message popup on top of the last error-less design:

**XAML Studio approach:**
![xaml-studio](https://user-images.githubusercontent.com/9091958/56461250-a8e79580-63c4-11e9-95a4-c504ca3224d9.gif)

**Comment by grokys** [comment]
Hi @0xaryan,

Yes this is actually a bug which was introduced by a bad merge undoing a change in the main avalonia repo just before the 0.8 release and unfortunately we didn't notice until after the release.


We'll hopefully be doing an 8.1 release soon which should fix this behavior, or you can run using the [CI nightly builds](https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed) and build your own version of AvaloniaVS from current master.
