### ISSUE TITLE
Show Available Avalonia Controls in the Controls Toolbox

### ISSUE THREAD

**Issue by TheColonel2688** [AvaloniaUI/AvaloniaVS#99]
Yes I know click and dragging controls is very doodleware-y and gross normally. But I was wanting to use Avalonia to create a Software HMI similar to [Advanced HMI](https://www.advancedhmi.com/index.php?main_page=page&id=14&chapter=0) but not using WinForms. Without Click and Drag and Hidden Controls, support like the WinForms editor as I am stuck.

**Comment by Gao996** [comment]
I develop with XAML only.
I can not find any controls in the left toolbox.
I want to drag and drop controls like wpf/winform

**Comment by maxkatz6** [comment]
Closing in favor of https://github.com/AvaloniaUI/AvaloniaVS/issues/148
